// scala.math.BigDecimal conversions: the implicit conversions at call sites and in expected
// types, Some(10) against Option[BigDecimal], Numeric through sum and sorted, the text form,
// hashes and equality against the primitive numbers, the isValid tests and toBigInt.
package bigdecimalconv

case class Price(amount: BigDecimal, discount: Option[BigDecimal])

def total(xs: BigDecimal*): BigDecimal = xs.sum
def half(x: BigDecimal): BigDecimal = x / 2

@main def main(): Unit =
  val a: BigDecimal = 10
  val b: BigDecimal = 2.5
  val c: BigDecimal = 7L
  println(s"$a $b $c")
  val p = Price(12, Some(10))
  println(p)
  println(Price(0.5, None))
  val o: Option[BigDecimal] = Some(3)
  println(o)
  println(half(5))
  println(half(1.25))
  println(total(1, 2.5, 3L))
  val xs = List[BigDecimal](3, 1.5, -2, 10, BigDecimal("0.001"))
  println(xs.sum)
  println(xs.product)
  println(xs.sorted)
  println(xs.max)
  println(xs.min)
  println(xs.sortBy(-_))
  println(Numeric[BigDecimal].plus(1, 2))
  println(Ordering[BigDecimal].compare(1, 2))
  println(summon[Fractional[BigDecimal]].div(1, 8))
  println(BigDecimal(1.1))
  println(BigDecimal(0.1))
  println(BigDecimal(1.0))
  println(BigDecimal(100.0))
  println(BigDecimal(1e-7))
  println(BigDecimal(1e7))
  println(BigDecimal(123456789.0))
  println(BigDecimal(1.0E23))
  println(BigDecimal(-0.001))
  println(BigDecimal.decimal(0.25))
  println(BigDecimal.exact(0.1))
  println(BigDecimal.exact(0.5))
  println(BigDecimal.valueOf(2.5))
  println(BigDecimal.valueOf(42L))
  println(BigDecimal(123456789012345L))
  println(BigDecimal(new java.math.BigDecimal("3.30")))
  println(BigDecimal("1e3"))
  println(BigDecimal("-.5"))
  println(BigDecimal("1.5E-10").toString)
  println(BigDecimal("1.20").underlying)
  println(BigDecimal("1.20").bigDecimal.scale)
  for s <- List("1", "1.0", "1.5", "-3", "100", "1E+2", "2147483648", "9223372036854775808", "0.1", "1E-400", "12345678901234567890.5") do
    val x = BigDecimal(s)
    val hash = if x.isWhole || !x.isDecimalDouble then x.hashCode.toString else s"double's ${x.hashCode == x.toDouble.##}"
    println(s"$s hash=$hash same=${x.hashCode == x.##} whole=${x.isWhole} int=${x.isValidInt} long=${x.isValidLong} dd=${x.isDecimalDouble} ed=${x.isExactDouble} bi=${x.toBigIntExact}")
  println(BigDecimal(1).hashCode == 1.hashCode)
  println(BigDecimal(1.5).hashCode == 1.5.##)
  println(BigDecimal(1) == 1)
  println(BigDecimal("1.0") == 1)
  println(BigDecimal("1.5") == 1.5)
  println(BigDecimal(2) == 2L)
  println(BigDecimal("0.1") == 0.1)
  println(BigDecimal(3) == BigInt(3))
  println(BigDecimal("3.5") == BigInt(3))
  println((1: Any) == BigDecimal(1))
  println((1.5: Any) == BigDecimal("1.50"))
  println((5L: Any) == BigDecimal(5))
  println(BigDecimal(1).equals(1))
  println(BigDecimal(1).equals("1"))
  println(Set[Any](BigDecimal("2.0"), BigDecimal(2)).size)
  println(Map(BigDecimal("1.0") -> "a")(BigDecimal(1)))
  println(BigDecimal("12.99").toInt + " " + BigDecimal("-12.99").toLong + " " + BigDecimal("12.75").toDouble)
  println(BigDecimal("1E+20").toLong)
  println(BigDecimal("12.5").intValue + " " + BigDecimal("12.5").longValue + " " + BigDecimal("0.25").floatValue)
  println(BigDecimal("12.99").toBigInt)
  println(BigDecimal("-12.99").toBigInt)
  println(BigDecimal("0.001").isValidInt)
  println(BigDecimal("5").toByte + " " + BigDecimal("300").toShort)
  val jbd: java.math.BigDecimal = new java.math.BigDecimal("4.20")
  val sbd: BigDecimal = jbd
  println(sbd * 2)
  println(List(BigDecimal(3), BigDecimal(1)).sum(using Numeric[BigDecimal]))
  println(Iterator(BigDecimal("0.5"), BigDecimal("0.25")).map(_ * 4).toList)
  println(2 * BigDecimal(3))
  println(1 + BigDecimal("0.5"))
  println(BigDecimal(1) + 2 * 3)
