// scala.math.BigInt: the operators, bit operations, pow, gcd, modPow, radix parsing and
// printing, toByteArray, conversions, hashes and equality.
package bigintops

def fact(n: Int): BigInt = if n <= 1 then 1 else fact(n - 1) * n

@main def main(): Unit =
  val a = BigInt("123456789012345678901234567890")
  val b = BigInt(-987654321)
  val c: BigInt = 42
  val d: BigInt = 10000000000L
  println(a + b)
  println(a - b)
  println(a * b)
  println(a / b)
  println(a % b)
  println(a /% b)
  println(-a)
  println(b.abs)
  println(s"${a.signum} ${b.signum} ${BigInt(0).signum}")
  println(a min b)
  println(a max b)
  println(c.pow(20))
  println(fact(30))
  println(a gcd BigInt(30))
  println(BigInt(-12) gcd BigInt(18))
  println(BigInt(-7) mod BigInt(3))
  println(BigInt(-7) % BigInt(3))
  println(BigInt(-7) / BigInt(3))
  println(BigInt(4).modPow(BigInt(13), BigInt(497)))
  println(BigInt(3).modInverse(BigInt(11)))
  println(c << 70)
  println(a >> 40)
  println(BigInt(-1000) >> 3)
  println(BigInt(-1000) << 3)
  println(BigInt(0xF0F0) & BigInt(0xFF00))
  println(BigInt(0xF0F0) | BigInt(0x0F0F))
  println(BigInt(0xF0F0) ^ BigInt(0xFFFF))
  println(BigInt(0xF0F0) &~ BigInt(0x00F0))
  println(BigInt(-6) & BigInt(13))
  println(BigInt(-6) | BigInt(13))
  println(BigInt(-6) ^ BigInt(13))
  println(~BigInt(5))
  println(s"${a.bitLength} ${b.bitLength} ${BigInt(-1).bitLength} ${BigInt(0).bitLength}")
  println(s"${a.bitCount} ${b.bitCount}")
  println(s"${c.testBit(1)} ${c.testBit(2)} ${BigInt(-2).testBit(100)}")
  println(s"${c.setBit(0)} ${c.clearBit(1)} ${c.flipBit(3)} ${BigInt(-1).clearBit(64)}")
  println(s"${c.lowestSetBit} ${BigInt(0).lowestSetBit} ${(BigInt(1) << 100).lowestSetBit}")
  println(s"${BigInt("ff", 16)} ${BigInt("-777", 8)} ${BigInt("zz", 36)} ${BigInt("101010", 2)}")
  println(s"${a.toString(16)} ${b.toString(2)} ${a.toString(36)} ${BigInt(-255).toString(16)}")
  println(BigInt("+15"))
  try BigInt("12x")
  catch case e: NumberFormatException => println("NumberFormatException: " + e.getMessage)
  try BigInt("")
  catch case e: NumberFormatException => println("NumberFormatException: " + e.getMessage)
  try BigInt(1) / BigInt(0)
  catch case e: ArithmeticException => println("ArithmeticException: " + e.getMessage)
  println(BigInt(255).toByteArray.mkString(","))
  println(BigInt(-129).toByteArray.mkString(","))
  println(BigInt(0).toByteArray.mkString(","))
  println(a.toByteArray.mkString(","))
  println(BigInt(Array[Byte](1, 0, 0)))
  println(BigInt(Array[Byte](-1, 0)))
  println(BigInt(-1, Array[Byte](1, 0)))
  println(s"${BigInt(97).isProbablePrime(20)} ${BigInt(91).isProbablePrime(20)} ${BigInt("170141183460469231731687303715884105727").isProbablePrime(50)}")
  println(s"${BigInt(2147483647).isValidInt} ${BigInt(2147483648L).isValidInt} ${d.isValidLong} ${(BigInt(1) << 63).isValidLong}")
  println(s"${a.toInt} ${a.toLong} ${d.toInt} ${BigInt(1000).toDouble.toInt}")
  println(s"${a.intValue} ${a.longValue} ${BigInt(3).floatValue == 3.0f}")
  println(s"${c.isValidByte} ${BigInt(200).isValidByte} ${BigInt(200).isValidShort} ${BigInt(70000).isValidChar}")
  println(s"${c.toByte} ${BigInt(300).toShort} ${BigInt(65).toChar}")
  println(s"${c.hashCode} ${d.hashCode} ${a.hashCode} ${b.##} ${(BigInt(1) << 64).##}")
  println(c == 42)
  println(c == 42L)
  println(c == 42.0)
  println(d == 10000000000L)
  println((42: Any) == c)
  println(c.equals(BigInt(42)))
  println(c.equals(42.5))
  println(BigInt(3) == BigDecimal(3))
  println((BigInt(1) << 60) == math.pow(2, 60))
  println(List[BigInt](5, -3, 10, 0).sorted)
  println(List[BigInt](5, -3, 10, 0).sum)
  println(List[BigInt](1, 2, 3, 4).product)
  println(s"${Integral[BigInt].quot(17, 5)} ${Integral[BigInt].rem(17, 5)}")
  println(Ordering[BigInt].max(1, 2))
  println(BigInt(17).compare(BigInt(5)))
  println(c < 43 && c > 41 && c <= 42 && c >= 42)
  println(Set(BigInt(1), BigInt(1L), BigInt("1")).size)
  println(BigInt(10).underlying.getClass.getName)
  println(BigInt(10).bigInteger)
  println(a.isWhole)
  println(s"${BigInt(7) + 1} ${(BigInt(7) * 2L)}")
  println(2 * BigInt(21))
  println(BigInt.long2bigInt(5L) + BigInt.int2bigInt(6))
  println(BigInt(new java.math.BigInteger("99")))
