// The failures of the lean std's collections on nothing, each the exception and message scala-library gives, a
// `catch` of the base type seeing them (the runtime's classes are linked by a `try`, whichever it names).
import scala.collection.mutable.ArrayBuffer
object Main:
  def show(label: String)(body: => Any): Unit =
    try { body; println(label + ": no failure") }
    catch case e: Exception => println(label + ": " + e.getClass.getName + ": " + e.getMessage)
  def main(args: Array[String]): Unit =
    show("list head")(List.empty[Int].head)
    show("list last")(List.empty[Int].last)
    show("list tail")(Nil.tail)
    show("list init")(List.empty[Int].init)
    show("list apply")(List(1)(5))
    show("seq head")(Seq.empty[Int].head)
    show("option head")(Option.empty[Int].head)
    show("option get")(Option.empty[Int].get)
    show("vector head")(Vector.empty[Int].head)
    show("vector last")(Vector.empty[Int].last)
    show("vector tail")(Vector.empty[Int].tail)
    show("vector init")(Vector.empty[Int].init)
    show("vector apply")(Vector.empty[Int](0))
    show("vector apply 5")(Vector(1)(5))
    show("array head")(Array.empty[Int].head)
    show("array last")(Array.empty[Int].last)
    show("array tail")(Array.empty[Int].tail)
    show("array init")(Array.empty[Int].init)
    show("iarray head")(IArray.empty[Int].head)
    show("iarray last")(IArray.empty[Int].last)
    show("string head")("".head)
    show("string last")("".last)
    show("string tail")("".tail)
    show("string init")("".init)
    show("set head")(Set.empty[Int].head)
    show("set last")(Set.empty[Int].last)
    show("set tail")(Set.empty[Int].tail)
    show("set init")(Set.empty[Int].init)
    show("map head")(Map.empty[Int, Int].head)
    show("map last")(Map.empty[Int, Int].last)
    show("map apply")(Map(1 -> 2)(3))
    show("buffer head")(ArrayBuffer.empty[Int].head)
    show("buffer last")(ArrayBuffer.empty[Int].last)
    show("buffer tail")(ArrayBuffer.empty[Int].tail)
    show("buffer init")(ArrayBuffer.empty[Int].init)
    show("buffer apply")(ArrayBuffer.empty[Int](0))
    show("buffer apply 5")(ArrayBuffer(1)(5))
    show("range head")((1 until 1).head)
    show("range last")((1 until 1).last)
    show("range tail")((1 until 1).tail)
    show("range init")((1 until 1).init)
    show("lazy head")(LazyList.empty[Int].head)
    show("lazy tail")(LazyList.empty[Int].tail)
    show("iterator next")(Iterator.empty[Int].next())
    show("iterator reduce")(Iterator.empty[Int].reduce(_ + _))
    show("set reduce")(Set.empty[Int].reduce(_ + _))
    show("list reduce")(List.empty[Int].reduce(_ + _))
    show("list max")(List.empty[Int].max)
    show("vector minBy")(Vector.empty[Int].minBy(x => x))
