// Math's integer members over Long at the ends of the range, where a result computed through a
// wrapped intermediate goes wrong: floorDiv and floorMod, the exact operations and their
// overflow messages, abs, max and min, and the Int of Java's floorMod(long, int).
@main def main(): Unit =
  println(Math.floorDiv(Long.MaxValue, -2L))
  println(Math.floorDiv(Long.MinValue, 3L))
  println(Math.floorDiv(Long.MinValue, -1L))
  println(Math.floorDiv(Long.MinValue, Long.MaxValue))
  println(Math.floorDiv(Long.MaxValue, Long.MinValue))
  println(Math.floorDiv(-7L, 2L))
  println(Math.floorDiv(7L, -2L))
  println(Math.floorDiv(6L, -2L))
  println(Math.floorMod(Long.MaxValue, -2L))
  println(Math.floorMod(Long.MinValue, 3L))
  println(Math.floorMod(Long.MinValue, -1L))
  println(Math.floorMod(Long.MinValue, Long.MaxValue))
  println(Math.floorDiv(Int.MinValue, -1))
  println(Math.floorDiv(Int.MaxValue, -2))
  println(Math.floorDiv(Int.MinValue, 3))
  println(Math.floorMod(Int.MinValue, 3))
  println(scala.math.floorDiv(Long.MaxValue, -2L))
  println(scala.math.floorMod(Long.MinValue, 3L))
  println(java.lang.Math.floorDiv(Long.MinValue, 3))
  println(java.lang.Math.floorMod(Long.MinValue, 3))
  println((java.lang.Math.floorMod(-7L, 3): Any).isInstanceOf[Int])
  println(java.lang.Math.addExact(Long.MaxValue - 1, 1L))
  println(java.lang.Math.addExact(4000000000L, 4000000000L))
  println(java.lang.Math.subtractExact(-4000000000L, 4000000000L))
  println(java.lang.Math.multiplyExact(4000000000L, 3L))
  println(java.lang.Math.multiplyExact(4000000000L, 3))
  println(java.lang.Math.negateExact(5L))
  println(java.lang.Math.negateExact(-5))
  println(java.lang.Math.toIntExact(-5L))
  def overflow(f: => Any): String = try f.toString catch case e: ArithmeticException => e.getMessage
  println(overflow(java.lang.Math.addExact(Long.MaxValue, 1L)))
  println(overflow(java.lang.Math.subtractExact(Long.MinValue, 1L)))
  println(overflow(java.lang.Math.multiplyExact(Long.MaxValue, 2L)))
  println(overflow(java.lang.Math.multiplyExact(Long.MaxValue, 2)))
  println(overflow(java.lang.Math.negateExact(Long.MinValue)))
  println(overflow(java.lang.Math.addExact(Int.MaxValue, 1)))
  println(overflow(java.lang.Math.subtractExact(Int.MinValue, 1)))
  println(overflow(java.lang.Math.multiplyExact(1 << 16, 1 << 16)))
  println(overflow(java.lang.Math.negateExact(Int.MinValue)))
  println(overflow(java.lang.Math.toIntExact(Long.MaxValue)))
  println(overflow(Math.floorDiv(1L, 0L)))
  println(overflow(Math.floorMod(1L, 0L)))
  println(Math.abs(Long.MinValue))
  println(Math.abs(Long.MinValue + 1))
  println(Math.max(9007199254740993L, 9007199254740992L))
  println(Math.min(9007199254740993L, 9007199254740992L))
  println(Long.MinValue.abs)
  println(Long.MinValue.sign)
  println(9007199254740993L.max(9007199254740992L))
