// The interpreter's strings count UTF-16 units as the JVM's do: a supplementary character is two
// units, a half of it taken apart is a lone surrogate that joins its other half again, and every
// native that takes or gives an index (substring, charAt, indexOf, slices, patch, search, hash
// and comparison) sees the units.
object Main:
  class Empty:
    override def toString = ""
  def show(s: String): String = s.map(c => f"${c.toInt}%04X").mkString("[", " ", "]") + s.length
  def main(args: Array[String]): Unit =
    val g = "𝄞"
    println(g.length)
    println(g.substring(0, 1).length)
    println(g.substring(1).length)
    println(show(g.substring(0, 1)))
    println(show(g.substring(1)))
    println(g.substring(0, 1) + g.substring(1) == g)
    println((g.substring(0, 1) + g.substring(1)).length)
    println(show(g.charAt(0).toString))
    println(show(g.charAt(1).toString))
    println(show(g.charAt(0).toString + g.charAt(1).toString))
    println(g.charAt(0).toString + g.charAt(1).toString == g)
    println(g.charAt(0).toInt)
    println(g.charAt(1).toInt)
    println(g.codePointAt(0))
    println(g.codePointAt(1))
    val s = "a𝄞b𝄞c"
    println(s.length)
    println(s.indexOf("b"))
    println(s.indexOf('c'))
    println(s.lastIndexOf("𝄞"))
    println(s.indexOf(g.substring(1)))
    println(s.indexOf(0xDD1E))
    println(s.indexOf(0x1D11E))
    println(show(s.take(2)))
    println(show(s.drop(2)))
    println(show(s.slice(2, 5)))
    println(s.splitAt(2)._1.length)
    println(show(s.splitAt(2)._2))
    println(show(s.patch(2, "X", 1)))
    println(show(s.reverse))
    println(s.reverse.reverse == s)
    println(show(s.substring(2, 5)))
    println(s.substring(2, 5).hashCode)
    println((g.substring(0, 1) + "x").hashCode)
    println(g.substring(0, 1).hashCode)
    println(g.hashCode)
    println(s.hashCode)
    println(g.substring(0, 1) == g.substring(0, 1))
    println(g.substring(0, 1) == g.substring(1))
    println(g.substring(0, 1).compareTo(g.substring(1)))
    println(g.substring(0, 1).compareTo("￿"))
    println(Set(g.substring(0, 1), g.substring(0, 1), g).size)
    println(Map(g.substring(0, 1) -> 1).get(g.charAt(0).toString))
    val sb = new StringBuilder
    sb.append(g.charAt(0)); sb.append(g.charAt(1))
    println(sb.toString == g)
    println(sb.length)
    val jb = new java.lang.StringBuilder
    jb.append(g.charAt(0)); jb.append(g.charAt(1))
    println(jb.toString == g)
    println(new String(Array(g.charAt(0), g.charAt(1))) == g)
    println(g.toCharArray.length)
    println(g.toCharArray.mkString == g)
    println(g.toList.length)
    println(g.toList.mkString == g)
    println(g.map(identity).length)
    println(g.filter(_ => true) == g)
    println(g.codePointCount(0, 2))
    println(g.codePointCount(0, 1))
    println(s.toSeq.length)
    println(s.count(c => java.lang.Character.isHighSurrogate(c)))
    println(s.count(c => java.lang.Character.isLowSurrogate(c)))
    println(java.lang.Character.isLowSurrogate(s.charAt(2)))
    println(java.lang.Character.isSurrogate(s.charAt(1)))
    println(s.split("b").map(_.length).toList)
    println(s.replace("b", "").length)
    println(s.replace(g.substring(1), "Z").length)
    println(show(s.replace(g.substring(1), "Z")))
    println(s.replace('b', 'q').length)
    println(s.contains(g.substring(0, 1)))
    println(s.startsWith(g.substring(0, 1), 1))
    println(s.endsWith(g.substring(1) + "c"))
    println(s.head)
    println(s.last)
    println(s(1).toInt)
    println(s.iterator.length)
    println(s.zipWithIndex.map(_._2).toList)
    println(s.indices.toList)
    println(s.foldLeft(0)((n, _) => n + 1))
    println(s.exists(_ == g.charAt(1)))
    println(s.updated(1, 'X').length)
    println(show(s.updated(1, 'X')))
    println(show(s.updated(2, 'X')))
    println(s.substring(1, 2) + s.substring(2, 3) == g)
    println(s.lastIndexOf(g.substring(1)))
    println(s.indexOf(g.substring(1), 3))
    println(g.substring(0, 1).trim.length)
    println(show(g.substring(0, 1).toUpperCase))
    println(show(g.toUpperCase))
    println(show("\uD834" + "\uDD1E"))
    println("\uD834" + "\uDD1E" == g)
    val hi = "\uD834"
    val lo = "\uDD1E"
    println((hi + lo).length)
    println((hi + lo) == g)
    println(show(hi.concat(lo)))
    println(hi.concat(lo) == g)
    println(List(hi, lo).mkString == g)
    println(s"$hi$lo" == g)
    println(Array(hi, lo).mkString("") == g)
    println(show(g.substring(0, 1) * 2))
    println(show(g.substring(1) + g.substring(0, 1)))
    println(show(g.substring(0,1).padTo(3, g.charAt(1))))
    println(show("x".padTo(3, g.charAt(0))))
    println(show(g.charAt(0).toString.repeat(2)))
    println(show(g.substring(0, 1).intern()))
    println(g.substring(0, 1).isEmpty)
    println(g.substring(0, 1).nonEmpty)
    println(g.indexOf(g.charAt(1).toInt))
    println(g.indexOf(g.charAt(0).toInt))
    println(g.sorted == g)
    println(show(g.sorted))
    println(show(g.distinct))
    println(g.contains(g.charAt(1)))
    val e = new Empty
    println(hi + e + lo == g)
    println(s"$hi$e$lo" == g)
    println((hi + e + lo).length)
    println((lo + hi) * 2 == lo + g + hi)
    println(show((lo + hi) * 2))
    println(show((lo + hi).repeat(2)))
    println("%s%s".format(hi, lo) == g)
    println(f"$hi%s$lo%s" == g)
    println(raw"$hi$lo" == g)
    println(Seq(hi, lo).mkString == g)
    println(Seq(hi, lo).mkString("", "", "") == g)
    println(("x" + hi).concat(lo + "y") == "x" + g + "y")
    println(show("%.1s".format(g)))
    println(show(String.format("%c", 0xD834)))
    println(g.stripPrefix(hi).length)
    println(g.stripSuffix(lo).length)
    println(show(g.stripPrefix(hi)))
    println(s.startsWith(hi))
    println(s.substring(1).startsWith(hi))
    println((hi + "a").endsWith(hi))
    println(new StringBuilder().append(hi).append(lo).toString == g)
    println(show(new StringBuilder(hi + "x" + lo).reverse.toString))
    println(show("%c".format(0x1D11E)))
    println(show(f"${0x1D11E}%c"))
    // A pair whose code point lies in the range the compiler keeps lone surrogates in stays two
    // units, however it is put together.
    val top = 0xdbfe.toChar.toString + 0xdc00.toChar.toString
    println(top.length)
    println(top.toCharArray.map(_.toInt).mkString(","))
    println("\uDBFE\uDC00".toCharArray.map(_.toInt).mkString(","))
    println(top == "\uDBFE\uDC00" && top == new String(Array(0xdbfe.toChar, 0xdc00.toChar)))
    println(top.codePointAt(0))
    println(("\uDBFF" + "\uDFFF").toCharArray.map(_.toInt).mkString(","))
    println(top.hashCode)
    println("\\uDBFE\\uDC00".r.findFirstIn(top).map(_.length))
    println(top.indexOf(0x10F800))
    println("%c".format(0x10F800).toCharArray.map(_.toInt).mkString(","))
    println(List(top.codePointCount(0, 2), new String(Array(0xdbff.toChar, 0xdfff.toChar)).codePointCount(0, 2), (top + "a" + g).codePointCount(0, 5), top.codePointCount(1, 2)))
