// The members of StringOps that take a count or an index at and past their bounds: `*` gives the
// empty string for a negative count where String.repeat throws, patch and updated give a String,
// sliding and grouped refuse a size or a step below one. Where Scala.js's message differs from
// the JVM's only the class is printed.
@main def main(): Unit =
  def at(f: => Any): Unit =
    try println("[" + f + "]")
    catch case e: Throwable => println("threw " + e.getClass.getName + ": " + e.getMessage)
  def cls(f: => Any): Unit =
    try println("[" + f + "]")
    catch case e: Throwable => println("threw " + e.getClass.getName)
  at("ab" * -1)
  at("ab" * Int.MinValue)
  at("ab" * 0)
  at("ab" * 3)
  at("" * 5)
  at("ab".repeat(0))
  cls("ab".repeat(-1))
  cls("".repeat(-1))
  at("abc".take(-1))
  at("abc".take(Int.MaxValue))
  at("abc".drop(-1))
  at("abc".drop(10))
  at("abc".takeRight(-1))
  at("abc".dropRight(-1))
  at("abc".dropRight(Int.MaxValue))
  at("abc".splitAt(-1))
  at("abc".splitAt(10))
  at("abc".padTo(-1, 'x'))
  at("abc".padTo(5, 'x'))
  at("abc".slice(-1, 2))
  at("abc".slice(2, 1))
  at("abc".slice(Int.MinValue, Int.MaxValue))
  at("abc".patch(-1, "X", 1))
  at("abc".patch(10, "X", 1))
  at("abc".patch(1, "X", -1))
  at("abc".patch(1, "xy", 1))
  at("abc".patch(1, List('x', 'y'), 1))
  at("abc".patch(1, List(1, 2), 1))
  at("abc".patch(0, "abcd", 7))
  cls("abc".patch(0, "", 5))
  at("abc".updated(1, 'X'))
  cls("abc".updated(3, 'X'))
  cls("abc".updated(-1, 'X'))
  at("abc".sliding(2).toList)
  at("abc".sliding(2, 2).toList)
  at("abc".sliding(5).toList)
  at("abc".sliding(0).toList)
  at("abc".sliding(2, 0).toList)
  at("abc".sliding(-1).toList)
  at("abcdef".grouped(4).toList)
  at(List(1, 2, 3).sliding(0).toList)
  at(List(1, 2, 3).grouped(0).toList)
  at(Vector(1, 2, 3).sliding(2, -1).toList)
  at(Iterator(1, 2, 3).grouped(-2).toList)
