import scala.util.Try
@main def main(): Unit =
  println("std stack safety, 100000 elements")
  val big = List.range(0, 100000)
  println(Try(big.map(_ + 1).length).isSuccess)
  println(Try(big.foldRight(0)(_ + _)).isSuccess)
  println(Try((big ++ big).length).isSuccess)
  println(Try(big.flatMap(x => List(x, x)).length).isSuccess)
  println(Try(big.filter(_ % 2 == 0).length).isSuccess)
  println(Try(big.reverse.length).isSuccess)
  println(Try(big.zip(big).length).isSuccess)
  println(Try(big.foldLeft(0)(_ + _)).isSuccess)
  println(Try(big.reduceRight(_ + _)).isSuccess)
  println(Try(big.toVector.map(_ + 1).length).isSuccess)
  println(Try(big.mkString(",").length).isSuccess)
  println(Try(big.toSet.size).isSuccess)
  println(Try(big.sorted.length).isSuccess)
  println(Try(big.groupBy(_ % 10).size).isSuccess)
  println(Try(big.distinct.length).isSuccess)
  println(Try(big.scanLeft(0)(_ + _).length).isSuccess)
  println(Try(big.sliding(2).length).isSuccess)
  println(Try(big.take(50000).length).isSuccess)
  println(Try(big.drop(50000).length).isSuccess)
  println(Try(big.exists(_ == 99999)).isSuccess)
  println(Try(big.hashCode).isSuccess)
  println(Try(big == big.map(identity)).isSuccess)
  println(Try(big.toString.length).isSuccess)
  println(Try((0 until 100000).toList.length).isSuccess)
  println(Try(List.fill(100000)(1).sum).isSuccess)
  println(Try(List.tabulate(100000)(identity).last).isSuccess)
  println(Try(big.iterator.map(_ + 1).toList.length).isSuccess)
  println(Try(big.map(Some(_)).flatten.length).isSuccess)
  println(Try(big.partition(_ % 2 == 0)._1.length).isSuccess)
  println(Try(big.span(_ < 50000)._2.length).isSuccess)
  println(Try(big.zipWithIndex.length).isSuccess)
  println(Try(big.indices.length).isSuccess)
  println(Try(big.updated(99999, 0).length).isSuccess)
  println(Try(big.splitAt(50000)._2.length).isSuccess)
  println(Try(big.grouped(100).length).isSuccess)
