// A view is traversed on demand, anew each time.
@main def main(): Unit =
  val v = List(1, 2, 3).view.map: x =>
    println("  map " + x)
    x * 2
  println("  view defined")
  println(v.toList)
  println(v.head)
  println(v.headOption)
  println(v)
  println(v.mkString(","))
  println(v.mkString)
  val failer = () => { println("  fail"); None }
  val succeeder = () => { println("  success"); Some(5) }
  val fs = List(failer, succeeder, failer, failer, succeeder)
  def f0 = fs.view.flatMap(f => f())
  println(f0.headOption)
  println(f0.lastOption)
  println(f0.last)
  println(List(1, 2, 3).view)
  println(Vector(1).view)
  println((1 to 3).view)
  println(Set(1).view)
  println(Map(1 -> 2).view)
  println(List(1, 2, 3).view.filter(_ > 1).map(_ * 10).toList)
  println(List(1, 2, 3).view.filter(_ > 1).map(_ * 10))
  println(List(1, 2, 3).view.take(2).drop(1).toList)
  println(List(1, 2, 3).view.zip(List(4, 5)).toList)
  println(List(1, 2, 3).view.zipWithIndex.toList)
  println(List(1, 2, 3).view.slice(1, 2).toList)
  println(List(1, 2, 3).view.takeWhile(_ < 3).toList)
  println(List(1, 2, 3).view.dropWhile(_ < 3).toList)
  println(List(1, 2, 3).view.scanLeft(0)(_ + _).toList)
  println(List(1, 2, 3).view.collect { case x if x > 1 => x }.toList)
  println(List(1, 2, 3).view.concat(List(4)).toList)
  println(List(1, 2, 3).view.updated(1, 8).toList)
  println(List(1, 2, 3).view.reverse.toList)
  println(List(1, 2, 3).view.sorted.toList)
  println(List(1, 2, 3).view.map(_ + 1).toSeq)
  println(List(1, 2, 3).view.force)
  println(s"${List(1, 2, 3).view.length} ${List(1, 2, 3).view.apply(1)} ${List(1, 2, 3).view.isEmpty} ${List(1, 2, 3).view.sum}")
  println(s"${List(1, 2, 3).view.toVector} ${List(1, 2, 3).view.toSet} ${Set(1, 2).view.toList}")
  val m = Map(1 -> "a", 2 -> "bb")
  println(m.view.mapValues(_.length).toMap)
  println(m.view.filterKeys(_ > 1).toMap)
  println(s"${m.view.mapValues(_.length).get(2)} ${m.view.mapValues(_.length).get(3)} ${m.view.filterKeys(_ > 1).get(1)} ${m.view.mapValues(_.length)(1)}")
  println(m.view.mapValues(_.length).toList)
  println(m.view.filter(_._1 == 1).toMap)
  println(s"${m.view.mapValues(_.length).keys.toList} ${m.view.mapValues(_.length).values.toList}")
  println(List("a", "bb").groupBy(_.length).view.mapValues(_.size).toMap)
  println(scala.collection.mutable.HashMap(1 -> 2).view.mapValues(_ + 1).toMap)
  val lazyMap = m.view.mapValues: s =>
    println("  mapValues " + s)
    s.length
  println("  mapValues defined")
  println(lazyMap.get(1))
  println(lazyMap.toMap)
