// jars: scala-library izumi-reflect-jvm izumi-reflect-boopickle-jvm
// A class with forty parents, whose tag izumi pickles over several of its pooled buffers: the
// buffers a run releases into `BufferPool`, a known cache, are the pool's, and a later run takes
// one and writes it from its start, then reads back what it wrote (`serializeIntoString` reads to
// the buffer's limit). Without the cache's stamp on what a run puts there, the next run's write
// gave the build to one worker at two and four workers.
trait P0[A]
trait P1[A]
trait P2[A]
trait P3[A]
trait P4[A]
trait P5[A]
trait P6[A]
trait P7[A]
trait P8[A]
trait P9[A]
trait P10[A]
trait P11[A]
trait P12[A]
trait P13[A]
trait P14[A]
trait P15[A]
trait P16[A]
trait P17[A]
trait P18[A]
trait P19[A]
trait P20[A]
trait P21[A]
trait P22[A]
trait P23[A]
trait P24[A]
trait P25[A]
trait P26[A]
trait P27[A]
trait P28[A]
trait P29[A]
trait P30[A]
trait P31[A]
trait P32[A]
trait P33[A]
trait P34[A]
trait P35[A]
trait P36[A]
trait P37[A]
trait P38[A]
trait P39[A]
class Big[A] extends P0[Int] with P1[Int] with P2[Int] with P3[Int] with P4[Int] with P5[Int] with P6[Int] with P7[Int] with P8[Int] with P9[Int] with P10[Int] with P11[Int] with P12[Int] with P13[Int] with P14[Int] with P15[Int] with P16[Int] with P17[Int] with P18[Int] with P19[Int] with P20[Int] with P21[Int] with P22[Int] with P23[Int] with P24[Int] with P25[Int] with P26[Int] with P27[Int] with P28[Int] with P29[Int] with P30[Int] with P31[Int] with P32[Int] with P33[Int] with P34[Int] with P35[Int] with P36[Int] with P37[Int] with P38[Int] with P39[Int]
