#!/usr/bin/env python3
"""Generates four programs whose macros run in the interpreter at thousands of call sites, so
that the cost of macro expansion can be measured without an application:

  python3 bench/macros/gen.py <dir>      writes <dir>/<program>/*.scala

  validate  a macro that validates class strings (`cls("flex p-2 md:hover:bg-red-500")`) against
            a catalog of 22,000 lines read from a file next to the sources: tokens split on
            whitespace and on `:` (brackets kept together), variants and bases looked up in
            sets and maps, duplicates and conflicts found by grouping; 4,000 sites
  derive    a derivation macro `Show.derived[C]` that walks the case fields of a class through
            `quotes.reflect`, summons an instance per field and builds an anonymous class in a
            quote with a selection per field; 200 case classes, 4,000 sites
  quotes    a quote-heavy macro that builds an arithmetic expression from nested quotes and
            simplifies it with quote patterns; 5,000 sites
  cls       the class-string validator of an application: `cls := (...)` over literals,
            conditional pairs and `Tw` values, classified through `quotes.reflect`, and a
            `tw"..."` interpolator read through `valueOrAbort`; each literal is tokenized by a
            fold over its characters and linted per token (banned forms, variant stacks,
            existence with suggestions, deprecation) and across tokens (duplicates, no-ops,
            conflicting signatures) against a 22,000-line vocabulary next to the sources, found
            by walking up the directories and cached by modification time; 4,000 sites

`bench/macros/run.sh` compiles them with `--profile` and reports the expansion time.
"""
import os
import random
import sys

random.seed(7)

COLORS = ["slate", "gray", "zinc", "neutral", "stone", "red", "orange", "amber", "yellow", "lime", "green", "emerald", "teal", "cyan", "sky", "blue", "indigo", "violet", "purple", "fuchsia", "pink", "rose"]
SHADES = ["50", "100", "200", "300", "400", "500", "600", "700", "800", "900", "950"]
COLOR_PROPS = ["text", "bg", "border", "ring", "from", "to", "via", "fill", "stroke", "outline", "decoration", "placeholder", "accent", "caret", "divide", "shadow"]
SPACING = ["0", "px", "0.5", "1", "1.5", "2", "2.5", "3", "3.5", "4", "5", "6", "7", "8", "9", "10", "11", "12", "14", "16", "20", "24", "28", "32", "36", "40", "44", "48", "52", "56", "60", "64", "72", "80", "96", "auto", "full", "1/2", "1/3", "2/3", "1/4", "3/4"]
SPACING_PROPS = ["p", "px", "py", "pt", "pr", "pb", "pl", "m", "mx", "my", "mt", "mr", "mb", "ml", "w", "h", "gap", "gap-x", "gap-y", "inset", "top", "right", "bottom", "left", "space-x", "space-y", "min-w", "max-w", "min-h", "max-h", "translate-x", "translate-y", "size", "basis", "scroll-m", "scroll-p", "indent", "start", "end", "-m", "-mx", "-my", "-mt", "-top", "-left"]
PLAIN = ["flex", "grid", "block", "inline", "hidden", "relative", "absolute", "fixed", "sticky", "truncate", "italic", "underline", "uppercase", "lowercase", "capitalize", "rounded", "rounded-md", "rounded-lg", "rounded-full", "shadow", "shadow-md", "shadow-lg", "border", "border-2", "cursor-pointer", "select-none", "overflow-hidden", "overflow-auto", "items-center", "items-start", "justify-center", "justify-between", "flex-col", "flex-row", "flex-wrap", "font-bold", "font-medium", "font-semibold", "text-sm", "text-xs", "text-lg", "text-xl", "text-2xl", "text-center", "text-left", "leading-tight", "tracking-wide", "whitespace-nowrap", "transition", "duration-150", "opacity-50", "z-10", "z-20"]
VARIANTS = ["hover", "focus", "active", "disabled", "first", "last", "odd", "even", "group-hover", "focus-within", "focus-visible", "visited", "checked", "placeholder", "before", "after", "print", "motion-safe", "rtl", "ltr"]
SCREENS = ["sm", "md", "lg", "xl", "2xl", "max-sm", "max-md", "max-lg"]


def catalog():
    """The class list: every class with its conflict group, the variants and the screens."""
    lines = ["# generated by bench/macros/gen.py"]
    group = 0
    for prop in COLOR_PROPS:
        group += 1
        for color in COLORS:
            for shade in SHADES:
                lines.append(f"class:{prop}-{color}-{shade}|{group}")
                lines.append(f"class:{prop}-{color}-{shade}/50|{group}")
    for prop in SPACING_PROPS:
        group += 1
        for value in SPACING:
            lines.append(f"class:{prop}-{value}|{group}")
    for name in PLAIN:
        group += 1
        lines.append(f"class:{name}|{group}")
    # Filler families up to the size of a real generated list.
    family = 0
    while len(lines) < 22000:
        group += 1
        for j in range(40):
            lines.append(f"class:u{family}-{j}|{group}")
        family += 1
    for v in VARIANTS:
        lines.append(f"variant:{v}")
    for s in SCREENS:
        lines.append(f"variant:{s}")
        lines.append(f"screen:{s}")
    for g in range(1, group + 1):
        lines.append(f"group:{g}|prop{g}")
    return "\n".join(lines) + "\n"


def class_string(used):
    """Tokens whose (variants, conflict group) pairs are distinct, so that the checks pass."""
    tokens = []
    n = random.randint(2, 6)
    while len(tokens) < n:
        kind = random.random()
        if kind < 0.35:
            base = random.choice(PLAIN)
            family = base
        elif kind < 0.7:
            family = random.choice(COLOR_PROPS)
            base = f"{family}-{random.choice(COLORS)}-{random.choice(SHADES)}"
        else:
            family = random.choice(SPACING_PROPS)
            base = f"{family}-{random.choice(SPACING)}"
        prefix = ""
        if random.random() < 0.3:
            prefix = random.choice(SCREENS) + ":"
        if random.random() < 0.25:
            prefix += random.choice(VARIANTS) + ":"
        if (prefix, family) in used:
            continue
        used.add((prefix, family))
        tokens.append(prefix + base)
    return " ".join(tokens)


VALIDATE_MACROS = '''package bench.validate

import java.nio.file.{Files, Path}
import java.util.concurrent.ConcurrentHashMap
import scala.jdk.CollectionConverters.*
import scala.quoted.*

final case class Token(raw: String, variants: List[String], base: String)

final case class Catalog(classes: Map[String, Int], variants: Set[String], screens: Set[String], groups: Map[Int, String])

object Catalog:
  private val cache = new ConcurrentHashMap[Path, Catalog]

  def near(source: Path): Option[Catalog] =
    def walk(dir: Path): Option[Path] =
      if dir == null then None
      else
        val candidate = dir.resolve("classes.txt")
        if Files.exists(candidate) then Some(candidate) else walk(dir.getParent)
    walk(source.getParent).map(file => cache.computeIfAbsent(file, parse))

  def parse(file: Path): Catalog =
    val lines = Files.readAllLines(file).asScala.toList.filter(line => line.nonEmpty && !line.startsWith("#"))
    def entries(prefix: String): List[String] = lines.filter(_.startsWith(prefix)).map(_.drop(prefix.length))
    def keyed(prefix: String): List[(String, String)] =
      entries(prefix).map: entry =>
        val i = entry.indexOf('|')
        if i < 0 then (entry, "") else (entry.take(i), entry.drop(i + 1))
    Catalog(
      classes = keyed("class:").map((name, group) => (name, group.toInt)).toMap,
      variants = entries("variant:").toSet,
      screens = entries("screen:").toSet,
      groups = keyed("group:").map((id, name) => (id.toInt, name)).toMap
    )

object Token:
  def parseAll(value: String): List[Token] =
    value.split("\\\\s+").toList.filter(_.nonEmpty).map(parse)

  def parse(token: String): Token =
    splitTopLevel(token, ':').reverse match
      case base :: variantsReversed => Token(token, variantsReversed.reverse, base)
      case Nil => Token(token, Nil, token)

  def splitTopLevel(token: String, separator: Char): List[String] =
    val (parts, current, _) = token.foldLeft((List.empty[String], "", 0)):
      case ((acc, cur, depth), '[') => (acc, cur + '[', depth + 1)
      case ((acc, cur, depth), ']') => (acc, cur + ']', 0.max(depth - 1))
      case ((acc, cur, 0), `separator`) => (cur :: acc, "", 0)
      case ((acc, cur, depth), other) => (acc, cur + other, depth)
    (current :: parts).reverse

object Checks:
  def token(t: Token, catalog: Catalog): List[String] =
    val unknownVariant = t.variants.find(v => !catalog.variants.contains(v)).map(v => s"unknown variant '$v' in '${t.raw}'")
    val unknownBase = Option.when(!catalog.classes.contains(t.base))(s"unknown class '${t.base}'")
    val repeated = t.variants.groupBy(identity).collectFirst:
      case (v, occurrences) if occurrences.length > 1 => s"variant '$v' repeated in '${t.raw}'"
    val screens = t.variants.filter(catalog.screens.contains)
    val stacked = screens match
      case a :: b :: _ => Some(s"'${t.raw}' stacks screens '$a' and '$b'")
      case _ => None
    List(unknownVariant, unknownBase, repeated, stacked).flatten

  def cross(tokens: List[Token], catalog: Catalog): List[String] =
    val keyed = tokens.map(t => (t, t.variants.sorted))
    val duplicates = keyed.groupBy((t, key) => (key, t.base)).values.toList.collect:
      case group if group.length > 1 => s"duplicate class '${group.head._1.raw}'"
    val conflicts = keyed.groupBy((_, key) => key).values.toList.flatMap: group =>
      group.flatMap((t, _) => catalog.classes.get(t.base).map(g => (t, g))).groupBy((_, g) => g).toList.flatMap: (g, same) =>
        same.map((t, _) => t) match
          case first :: second :: _ => Some(s"'${first.raw}' and '${second.raw}' conflict on ${catalog.groups.getOrElse(g, "?")}")
          case _ => None
    duplicates ++ conflicts

object Impl:
  def cls(classes: Expr[Seq[String]])(using Quotes): Expr[String] =
    import quotes.reflect.*
    val literals = classes match
      case Varargs(items) => items.flatMap(_.value).toList
      case _ => report.errorAndAbort("literal class strings expected", classes)
    val Some(source) = Position.ofMacroExpansion.sourceFile.getJPath: @unchecked
    val catalog = Catalog.near(source).getOrElse(report.errorAndAbort("no classes.txt next to the sources"))
    val tokens = literals.flatMap(Token.parseAll)
    val errors = tokens.flatMap(Checks.token(_, catalog)) ++ Checks.cross(tokens, catalog)
    if errors.nonEmpty then report.errorAndAbort(errors.distinct.mkString("\\n"), Position.ofMacroExpansion)
    Expr(tokens.map(_.raw).mkString(" "))

object Cls:
  inline def cls(inline classes: String*): String = ${ Impl.cls('classes) }
'''


def validate(sites):
    out = ["package bench.validate\n\n"]
    for i in range(sites):
        if i % 500 == 0:
            out.append(f"object Sites{i // 500}:\n")
        used = set()
        args = ", ".join(f'"{class_string(used)}"' for _ in range(random.randint(1, 2)))
        out.append(f"  def s{i}: String = Cls.cls({args})\n")
    out.append("\nobject Main:\n  def main(args: Array[String]): Unit =\n    println(Sites0.s0.length + Sites1.s500.length)\n")
    return "".join(out)


DERIVE_MACROS = '''package bench.derive

import scala.quoted.*

trait Show[T]:
  def show(t: T): String

object Show:
  given Show[Int] with
    def show(t: Int): String = t.toString
  given Show[String] with
    def show(t: String): String = "\\"" + t + "\\""
  given Show[Boolean] with
    def show(t: Boolean): String = t.toString
  given Show[Double] with
    def show(t: Double): String = t.toString

  inline def derived[T]: Show[T] = ${ derivedImpl[T] }

  def derivedImpl[T: Type](using Quotes): Expr[Show[T]] =
    import quotes.reflect.*
    val tpe = TypeRepr.of[T]
    val sym = tpe.typeSymbol
    if !sym.flags.is(Flags.Case) then report.errorAndAbort(s"${tpe.show} is not a case class")
    val fields = sym.caseFields
    val label = Expr(sym.name)
    def fieldShows(t: Expr[T]): List[Expr[String]] =
      fields.map: field =>
        val fieldType = tpe.memberType(field)
        fieldType.asType match
          case '[ft] =>
            val instance = Expr.summon[Show[ft]].getOrElse(report.errorAndAbort(s"no Show for ${fieldType.show}"))
            val value = Select(t.asTerm, field).asExprOf[ft]
            val name = Expr(field.name)
            '{ $name + "=" + $instance.show($value) }
    '{
      new Show[T]:
        def show(t: T): String =
          $label + ${ Expr.ofList(fieldShows('t)) }.mkString("(", ", ", ")")
    }
'''


def derive(classes, sites):
    types = ["Int", "String", "Boolean", "Double"]
    out = ["package bench.derive\n\n"]
    values = []
    for c in range(classes):
        n = random.randint(2, 6)
        fields = []
        args = []
        for f in range(n):
            if c > 0 and random.random() < 0.2:
                other = random.randrange(c)
                fields.append(f"f{f}: C{other}")
                args.append(f"V.v{other}")
            else:
                t = random.choice(types)
                fields.append(f"f{f}: {t}")
                args.append({"Int": str(f), "String": f'"s{f}"', "Boolean": "true", "Double": f"{f}.5"}[t])
        out.append(f"final case class C{c}({', '.join(fields)})\nobject C{c}:\n  given Show[C{c}] = Show.derived\n")
        values.append(f"  val v{c} = C{c}({', '.join(args)})\n")
    out.append("\nobject V:\n" + "".join(values) + "\n")
    for i in range(sites):
        if i % 500 == 0:
            out.append(f"object Sites{i // 500}:\n")
        c = i % classes
        out.append(f"  def s{i}: String = Show.derived[C{c}].show(V.v{c})\n")
    out.append("\nobject Main:\n  def main(args: Array[String]): Unit =\n    println(Sites0.s0 + Sites1.s500)\n")
    return "".join(out)


QUOTES_MACROS = '''package bench.quotes

import scala.quoted.*

object Poly:
  inline def poly(inline x: Int): Int = ${ polyImpl('x) }

  // ((x * a + b) * c + d) ... eight levels deep, then simplified by quote patterns: constant
  // factors of one and terms of zero fold away, constant subexpressions are evaluated.
  def polyImpl(x: Expr[Int])(using Quotes): Expr[Int] =
    var e = x
    var i = 0
    while i < 8 do
      val a = Expr(if i % 3 == 0 then 1 else i + 2)
      val b = Expr(if i % 2 == 0 then 0 else i)
      e = '{ $e * $a + $b }
      i += 1
    simplify(e)

  def simplify(e: Expr[Int])(using Quotes): Expr[Int] = e match
    case '{ ($a: Int) * 1 } => simplify(a)
    case '{ ($a: Int) + 0 } => simplify(a)
    case '{ ($a: Int) * ($b: Int) } =>
      (simplify(a), simplify(b)) match
        case (Expr(p), Expr(q)) => Expr(p * q)
        case (p, q) => '{ $p * $q }
    case '{ ($a: Int) + ($b: Int) } =>
      (simplify(a), simplify(b)) match
        case (Expr(p), Expr(q)) => Expr(p + q)
        case (p, q) => '{ $p + $q }
    case other => other
'''


def quotes(sites):
    out = ["package bench.quotes\n\n"]
    for i in range(sites):
        if i % 500 == 0:
            out.append(f"object Sites{i // 500}:\n")
        out.append(f"  def s{i}(x: Int): Int = Poly.poly(x + {i % 97})\n")
    out.append("\nobject Main:\n  def main(args: Array[String]): Unit =\n    println(Sites0.s0(1) + Sites1.s500(2))\n")
    return "".join(out)

CLS_MACROS = '''package bench.cls

import java.nio.file.attribute.FileTime
import java.nio.file.{Files, Path}
import java.util.concurrent.ConcurrentHashMap
import scala.annotation.tailrec
import scala.jdk.CollectionConverters.*
import scala.quoted.*

object Styles:
  opaque type Tw = String

  object Tw:
    val empty: Tw = ""
    extension (classes: Tw)
      inline def raw: String = classes
      def ++(other: Tw): Tw = if classes.isEmpty then other else if other.isEmpty then classes else classes + " " + other

  final case class Attr(value: String)

  extension (inline sc: StringContext)
    inline def tw(inline args: Any*): Tw = ${ Impl.twImpl('sc, 'args) }

  object cls:
    inline def :=(inline classes: (String | (String, Boolean) | Tw | (Tw, Boolean))*): Attr = ${ Impl.clsImpl('classes) }

  def join(classes: Seq[String | (String, Boolean) | Tw | (Tw, Boolean)]): Attr =
    val names = classes.flatMap:
      case (name: String, cond: Boolean) => Option.when(cond)(name)
      case name: String => Some(name)
    Attr(names.filter(_.nonEmpty).mkString(" "))

object Impl:
  type Arg = String | (String, Boolean) | Styles.Tw | (Styles.Tw, Boolean)

  def clsImpl(classes: Expr[Seq[Arg]])(using Quotes): Expr[Styles.Attr] =
    Args.validate(classes)
    '{ Styles.join($classes) }

  def twImpl(sc: Expr[StringContext], args: Expr[Seq[Any]])(using Quotes): Expr[String] =
    import quotes.reflect.*
    Args.rejectInterpolation(args)
    val value = StringContext.processEscapes(sc.valueOrAbort.parts.headOption.getOrElse(""))
    Report.withVocabulary(Position.ofMacroExpansion): vocabulary =>
      val lexemes = Lexeme.parseAll(value)
      Report.all(lexemes.flatMap(Lint.single(_, vocabulary)) ++ Lint.together(lexemes, vocabulary), Position.ofMacroExpansion)
    Expr(value)

// The arguments of `cls := (...)`: literals are checked where they are written, `Tw` values were
// checked where they were made, anything else is an error.
object Args:
  private val splicedMessage = "an interpolated class string cannot be checked at compile time"
  private val runtimeMessage = "a dynamic class string cannot be checked at compile time"

  def rejectInterpolation(using Quotes)(args: Expr[Seq[Any]]): Unit =
    import quotes.reflect.*
    args match
      case Varargs(interpolated) if interpolated.nonEmpty => report.errorAndAbort(splicedMessage, Position.ofMacroExpansion)
      case _ => ()

  def validate(using Quotes)(classes: Expr[Seq[Impl.Arg]]): Unit =
    import quotes.reflect.*
    val twType = TypeRepr.of[Styles.Tw]
    case class Static(value: String, pos: Position, conditional: Boolean)

    @tailrec
    def unwrap(term: Term): Term = term match
      case Typed(inner, _) => unwrap(inner)
      case Block(Nil, inner) => unwrap(inner)
      case TypeApply(Select(inner, "$asInstanceOf$"), _) => unwrap(inner)
      case _ => term

    @tailrec
    def unwrapInlined(term: Term): Term = unwrap(term) match
      case Inlined(_, _, inner) => unwrapInlined(inner)
      case other => other

    object Pair:
      def unapply(term: Term): Option[(Term, Term)] = term match
        case Apply(TypeApply(Select(tuple, "apply"), _), List(a, b)) if tuple.symbol.fullName == "scala.Tuple2" => Some((a, b))
        case Apply(Select(tuple, "apply"), List(a, b)) if tuple.symbol.fullName == "scala.Tuple2" => Some((a, b))
        case Apply(TypeApply(Select(arrow, "->"), _), List(b)) =>
          unwrapInlined(arrow) match
            case Apply(_, List(a)) => Some((a, b))
            case _ => None
        case _ => None

    def isSpliced(term: Term): Boolean =
      val finder = new TreeAccumulator[Boolean]:
        def foldTree(found: Boolean, tree: Tree)(owner: Symbol): Boolean =
          found || (tree match
            case Apply(Select(sc, "apply"), _) if sc.symbol.fullName == "scala.StringContext" => true
            case _ => foldOverTree(found, tree)(owner))
      finder.foldTree(false, term)(Symbol.spliceOwner)

    @tailrec
    def isTw(term: Term): Boolean = unwrap(term) match
      case Inlined(Some(call: Term), _, _) => call.tpe <:< twType
      case Inlined(_, _, inner) => isTw(inner)
      case other => other.tpe <:< twType

    @tailrec
    def classify(term: Term, conditional: Boolean): Option[Static] =
      if isTw(term) then None
      else
        unwrapInlined(term) match
          case literal @ Literal(StringConstant(value)) => Some(Static(value, literal.pos, conditional))
          case Pair(a, _) if !conditional => classify(a, conditional = true)
          case other =>
            report.error(if isSpliced(other) then splicedMessage else runtimeMessage, other.pos)
            None

    val args = unwrapInlined(classes.asTerm) match
      case Repeated(elements, _) => elements
      case _ =>
        report.error("list the classes as separate arguments", classes.asTerm.pos)
        Nil

    Report.withVocabulary(Position.ofMacroExpansion): vocabulary =>
      val statics = args.flatMap(classify(_, conditional = false))
      val lexed = statics.map(static => (static, Lexeme.parseAll(static.value)))
      lexed.foreach: (static, lexemes) =>
        val together = if static.conditional then Lint.together(lexemes, vocabulary) else Nil
        Report.all(lexemes.flatMap(Lint.single(_, vocabulary)) ++ together, static.pos)
      val unconditional = lexed.filter((static, _) => !static.conditional)
      val pos = unconditional match
        case (single, _) :: Nil => single.pos
        case _ => Position.ofMacroExpansion
      Report.all(Lint.together(unconditional.flatMap((_, lexemes) => lexemes), vocabulary), pos)

object Report:
  def withVocabulary(using Quotes)(pos: quotes.reflect.Position)(check: Vocabulary => Unit): Unit =
    import quotes.reflect.*
    pos.sourceFile.getJPath match
      case None => ()
      case Some(source) =>
        Vocabularies.near(source) match
          case Some(vocabulary) => check(vocabulary)
          case None => report.error(s"no ${Vocabularies.FileName} above ${pos.sourceFile.path}", pos)

  def all(using Quotes)(messages: List[String], pos: quotes.reflect.Position): Unit =
    import quotes.reflect.*
    if messages.nonEmpty then report.error(messages.distinct.mkString("\\n"), pos)

// One whitespace-separated token: `md:hover:flex` has the variants `md` and `hover` and the
// base `flex`; brackets keep their contents together (`w-[calc(1px+2px)]`, `[&:nth-child(3)]:x`).
final case class Lexeme(raw: String, variants: List[String], base: String)

object Lexeme:
  def parseAll(value: String): List[Lexeme] =
    value.split("\\\\s+").toList.filter(_.nonEmpty).map(parse)

  def parse(raw: String): Lexeme =
    splitOutsideBrackets(raw, ':').reverse match
      case base :: variantsReversed => Lexeme(raw, variantsReversed.reverse, base)
      case Nil => Lexeme(raw, Nil, raw)

  def splitOutsideBrackets(text: String, separator: Char): List[String] =
    val (parts, current, _) = text.foldLeft((List.empty[String], "", 0)):
      case ((acc, cur, depth), '[') => (acc, cur + '[', depth + 1)
      case ((acc, cur, depth), ']') => (acc, cur + ']', 0.max(depth - 1))
      case ((acc, cur, 0), `separator`) => (cur :: acc, "", 0)
      case ((acc, cur, depth), other) => (acc, cur + other, depth)
    (current :: parts).reverse

  def bareVariant(variant: String): String =
    splitOutsideBrackets(variant, '/') match
      case first :: _ => first
      case Nil => variant

  def splitVariant(base: String): Option[(String, String)] =
    splitOutsideBrackets(base, '/').reverse match
      case modifier :: rootParts if rootParts.nonEmpty => Some((rootParts.reverse.mkString("/"), modifier))
      case _ => None

  def bracketRoot(base: String): Option[String] =
    val idx = base.indexOf("-[")
    Option.when(idx > 0 && base.endsWith("]"))(base.take(idx))

// The classes.txt next to the sources: classes with the signature of the properties they set,
// the signatures, the variants and their roots, the modifiers, the screens, the deprecations.
final case class Vocabulary(
  classes: Map[String, Option[Int]],
  signatures: Map[Int, String],
  variants: Set[String],
  variantRoots: Set[String],
  modifiers: Set[String],
  screensMin: Set[String],
  screensMax: Set[String],
  deprecated: Map[String, String]
):
  val bracketRoots: Map[String, Set[Int]] =
    classes.toList
      .flatMap: (name, signature) =>
        name.indices.filter(i => i > 0 && name.charAt(i) == '-').map(i => (name.take(i), signature))
      .groupMap((root, _) => root)((_, signature) => signature)
      .view
      .mapValues(_.flatten.toSet)
      .toMap

object Vocabulary:
  def parse(file: Path): Vocabulary =
    val lines = Files.readAllLines(file).asScala.toList.filter(line => line.nonEmpty && !line.startsWith("#"))
    def entries(prefix: String): List[String] = lines.filter(_.startsWith(prefix)).map(_.drop(prefix.length))
    def keyed(prefix: String): List[(String, String)] =
      entries(prefix).map: entry =>
        entry.indexOf('|') match
          case -1 => (entry, "")
          case i => (entry.take(i), entry.drop(i + 1))
    Vocabulary(
      classes = keyed("class:").map((name, sig) => (name, Option.when(sig.nonEmpty)(sig.toInt))).toMap,
      signatures = keyed("sig:").map((id, props) => (id.toInt, props)).toMap,
      variants = entries("variant:").toSet,
      variantRoots = entries("variantroot:").toSet,
      modifiers = entries("modifier:").toSet,
      screensMin = entries("screenmin:").toSet,
      screensMax = entries("screenmax:").toSet,
      deprecated = keyed("deprecated:").toMap
    )

// Parsed vocabularies are kept per file while its modification time stays; the nearest file
// is remembered per source directory.
object Vocabularies:
  val FileName = "classes.txt"

  private final case class Loaded(modified: FileTime, vocabulary: Vocabulary)

  private val loaded = new ConcurrentHashMap[Path, Loaded]
  private val closestFile = new ConcurrentHashMap[Path, Path]

  def near(source: Path): Option[Vocabulary] =
    Option(source.getParent).flatMap(nearest).map(load)

  private def nearest(dir: Path): Option[Path] =
    Option(closestFile.get(dir)).orElse:
      val found = LazyList
        .iterate(Option(dir))(_.flatMap(d => Option(d.getParent)))
        .takeWhile(_.isDefined)
        .flatten
        .map(_.resolve(FileName))
        .find(Files.exists(_))
      found.foreach(closestFile.put(dir, _))
      found

  private def load(file: Path): Vocabulary =
    val modified = Files.getLastModifiedTime(file)
    loaded
      .compute(file, (_, previous) => Option(previous).filter(_.modified.compareTo(modified) == 0).getOrElse(Loaded(modified, Vocabulary.parse(file))))
      .vocabulary

object Resolve:
  def modifierRoot(base: String, vocabulary: Vocabulary): Option[String] =
    Lexeme.splitVariant(base).map((root, _) => root).filter(vocabulary.classes.contains)

  def signature(base: String, vocabulary: Vocabulary): Option[Int] =
    vocabulary.classes.get(modifierRoot(base, vocabulary).getOrElse(base)).flatten.orElse(arbitrarySignature(base, vocabulary))

  private def arbitrarySignature(base: String, vocabulary: Vocabulary): Option[Int] =
    Lexeme.bracketRoot(base).flatMap(vocabulary.bracketRoots.get).flatMap: signatures =>
      signatures.toList match
        case signature :: Nil => Some(signature)
        case _ => None

object Shape:
  def isVariant(variant: String, vocabulary: Vocabulary): Boolean =
    val bare = Lexeme.bareVariant(variant)
    vocabulary.variants(bare)
      || (bare.startsWith("[") && bare.endsWith("]"))
      || (bare.endsWith("]") && vocabulary.variantRoots.exists(root => bare.startsWith(root + "-[") || bare.startsWith(root + "[")))

  def isBase(base: String, vocabulary: Vocabulary): Boolean =
    isPlain(base, vocabulary) || Lexeme.splitVariant(base).exists: (root, modifier) =>
      isPlain(root, vocabulary) && isModifier(modifier, root, vocabulary)

  private def isPlain(base: String, vocabulary: Vocabulary): Boolean =
    vocabulary.classes.contains(base) || (base.startsWith("[") && base.endsWith("]")) || hasArbitraryRoot(base, vocabulary)

  private def hasArbitraryRoot(base: String, vocabulary: Vocabulary): Boolean =
    Lexeme.bracketRoot(base).exists(root => vocabulary.classes.contains(root) || vocabulary.bracketRoots.contains(root))

  private def isModifier(modifier: String, root: String, vocabulary: Vocabulary): Boolean =
    root == "group" || root == "peer" || vocabulary.modifiers(modifier) || (modifier.startsWith("[") && modifier.endsWith("]"))

object Suggest:
  def text(token: String, candidates: Set[String]): String =
    val near = candidates.toList
      .filter(candidate => (candidate.length - token.length).abs <= 2)
      .map(candidate => candidate -> distance(token, candidate))
      .filter((_, d) => d <= 2)
      .sortBy((candidate, d) => (d, candidate))
      .take(3)
      .map((candidate, _) => candidate)
    if near.isEmpty then "" else near.mkString(" Did you mean: ", ", ", "?")

  private def distance(a: String, b: String): Int =
    val lastRow = a.foldLeft((0 to b.length).toList): (previousRow, charA) =>
      b.toList.zip(previousRow.zip(previousRow.drop(1))).scanLeft(previousRow.headOption.getOrElse(0) + 1):
        case (left, (charB, (diagonal, above))) => (left + 1).min(above + 1).min(diagonal + (if charA == charB then 0 else 1))
    lastRow.lastOption.getOrElse(0)

// Per token: banned forms, repeated or stacked variants, existence, deprecation. Across the
// tokens that apply together: duplicates, no-op copies, conflicting signatures, truncation.
object Lint:
  def single(lexeme: Lexeme, vocabulary: Vocabulary): List[String] =
    val bare = lexeme.variants.map(Lexeme.bareVariant)
    val important = Option.when(lexeme.base.startsWith("!"))(s"'${lexeme.raw}': the important modifier is not allowed")
    val dark = Option.when(bare.contains("dark"))(s"'${lexeme.raw}': the dark variant is not allowed")
    val repeated = bare.groupBy(identity).collectFirst:
      case (variant, occurrences) if occurrences.sizeIs > 1 => s"'${lexeme.raw}': variant '$variant:' is repeated"
    val known = if important.isEmpty then unknown(lexeme, vocabulary) else None
    List(important, dark, repeated, stackedScreens(lexeme, bare, vocabulary), known, deprecation(lexeme, vocabulary)).flatten

  private def stackedScreens(lexeme: Lexeme, bare: List[String], vocabulary: Vocabulary): Option[String] =
    def stacked(axis: Set[String], kind: String): Option[String] =
      bare.distinct.filter(axis) match
        case first :: second :: _ => Some(s"'${lexeme.raw}' stacks $kind-width screens '$first:' and '$second:'")
        case _ => None
    stacked(vocabulary.screensMin, "min").orElse(stacked(vocabulary.screensMax, "max"))

  private def unknown(lexeme: Lexeme, vocabulary: Vocabulary): Option[String] =
    lexeme.variants
      .find(variant => !Shape.isVariant(variant, vocabulary))
      .map(variant => s"unknown variant '$variant' in '${lexeme.raw}'${Suggest.text(Lexeme.bareVariant(variant), vocabulary.variants)}")
      .orElse:
        if Shape.isBase(lexeme.base, vocabulary) then None
        else Some(s"unknown class '${lexeme.base}'${Suggest.text(lexeme.base, vocabulary.classes.keySet)}")

  private def deprecation(lexeme: Lexeme, vocabulary: Vocabulary): Option[String] =
    vocabulary.deprecated
      .get(lexeme.base)
      .orElse(Resolve.modifierRoot(lexeme.base, vocabulary).flatMap(vocabulary.deprecated.get))
      .map(message => s"'${lexeme.raw}' is deprecated: $message")

  def together(lexemes: List[Lexeme], vocabulary: Vocabulary): List[String] =
    val keyed = lexemes.map(lexeme => (lexeme, lexeme.variants.map(Lexeme.bareVariant).sorted))
    val groups = keyed.groupBy((_, key) => key).values.toList.map(_.map((lexeme, _) => lexeme))
    duplicates(keyed) ++ noOps(keyed) ++ groups.flatMap(conflicts(_, vocabulary)) ++ groups.flatMap(truncated(_, vocabulary))

  private def duplicates(keyed: List[(Lexeme, List[String])]): List[String] =
    keyed.groupBy((lexeme, key) => (key, lexeme.base)).values.toList.collect:
      case group if group.sizeIs > 1 =>
        group.map((lexeme, _) => lexeme.raw).distinct match
          case raw :: Nil => s"duplicate class '$raw'"
          case raws => s"${raws.map(raw => s"'$raw'").mkString(" and ")} are the same class"

  private def noOps(keyed: List[(Lexeme, List[String])]): List[String] =
    keyed.groupBy((lexeme, _) => lexeme.base).values.toList.flatMap: group =>
      group.flatMap: (lexeme, key) =>
        val variants = key.toSet
        group.collectFirst:
          case (other, otherKey) if otherKey.toSet != variants && otherKey.toSet.subsetOf(variants) =>
            s"'${lexeme.raw}' is a no-op next to '${other.raw}'"

  private def conflicts(group: List[Lexeme], vocabulary: Vocabulary): List[String] =
    if group.sizeIs < 2 then Nil
    else
      group
        .distinctBy(_.base)
        .flatMap(lexeme => Resolve.signature(lexeme.base, vocabulary).map(sig => (lexeme, sig)))
        .groupBy((_, sig) => sig)
        .toList
        .flatMap: (sig, same) =>
          same.map((lexeme, _) => lexeme) match
            case first :: second :: _ => Some(s"'${first.raw}' and '${second.raw}' both set {${vocabulary.signatures.getOrElse(sig, "?")}}")
            case _ => None

  private val Wrapping = Set("white-space", "word-break", "overflow-wrap", "text-wrap")

  private def truncated(group: List[Lexeme], vocabulary: Vocabulary): List[String] =
    if !group.exists(_.base == "truncate") then Nil
    else
      group
        .filter(_.base != "truncate")
        .find: lexeme =>
          vocabulary.classes.get(lexeme.base).flatten.exists(sig => vocabulary.signatures.get(sig).exists(_.split(",").forall(Wrapping)))
        .map(lexeme => s"'${lexeme.base}' has no effect next to 'truncate'")
        .toList
'''

VARIANT_ROOTS = ["group-hover", "peer-checked", "aria", "data", "has"]
MODIFIERS = ["0", "5", "10", "20", "25", "30", "40", "50", "60", "70", "75", "80", "90", "95", "100"]
DEPRECATED_COLORS = ["fuchsia", "rose"]


def vocabulary():
    """The class list of the `cls` program: every class with its signature, the signatures, the
    variants, their roots, the modifiers, the screens and the deprecated palettes; 22,000
    lines like an application's."""
    lines = ["# generated by bench/macros/gen.py"]
    sig = 0
    props = {}
    for prop in COLOR_PROPS:
        sig += 1
        props[sig] = f"{prop}-color"
        for color in COLORS:
            for shade in SHADES:
                lines.append(f"class:{prop}-{color}-{shade}|{sig}")
                if shade == "500":
                    lines.append(f"class:{prop}-{color}-{shade}/50|{sig}")
    for prop in SPACING_PROPS:
        sig += 1
        props[sig] = f"{prop.strip('-')}-size"
        for value in SPACING:
            lines.append(f"class:{prop}-{value}|{sig}")
    for name in PLAIN:
        sig += 1
        props[sig] = name.split("-")[0]
        lines.append(f"class:{name}|{sig}")
    family = 0
    while len(lines) < 22000:
        sig += 1
        props[sig] = f"u{family}"
        for j in range(40):
            lines.append(f"class:u{family}-{j}|{sig}")
        family += 1
    for s, p in props.items():
        lines.append(f"sig:{s}|{p}")
    for v in VARIANTS + SCREENS:
        lines.append(f"variant:{v}")
    for r in VARIANT_ROOTS:
        lines.append(f"variantroot:{r}")
    for m in MODIFIERS:
        lines.append(f"modifier:{m}")
    for s in SCREENS:
        lines.append(f"screenmax:{s}" if s.startswith("max-") else f"screenmin:{s}")
    for prop in COLOR_PROPS:
        for color in DEPRECATED_COLORS:
            for shade in SHADES:
                lines.append(f"deprecated:{prop}-{color}-{shade}|the {color} palette is deprecated, use a semantic token")
    return "\n".join(lines) + "\n"


LIVE_COLORS = [c for c in COLORS if c not in DEPRECATED_COLORS]


def cls_literal(used, n=None):
    """A class string of 2 to 6 tokens with distinct families under distinct variants, some
    with a modifier (`bg-red-500/50`), an arbitrary value (`w-[13px]`) or a named group
    (`group-hover/menu:x`), so that every check passes."""
    tokens = []
    bases = set()
    n = n or random.randint(2, 6)
    while len(tokens) < n:
        kind = random.random()
        if kind < 0.35:
            base = random.choice(PLAIN)
            family = base
        elif kind < 0.7:
            family = random.choice(COLOR_PROPS)
            shade = random.choice(SHADES)
            base = f"{family}-{random.choice(LIVE_COLORS)}-{shade}"
            if shade == "500" and random.random() < 0.3:
                base += "/50"
        else:
            family = random.choice(SPACING_PROPS)
            base = f"{family}-{random.choice(SPACING)}" if random.random() > 0.08 else f"{family}-[{random.randint(1, 99)}px]"
        prefix = ""
        if random.random() < 0.3:
            prefix = random.choice(SCREENS) + ":"
        if random.random() < 0.25:
            variant = random.choice(VARIANTS)
            if variant == "group-hover" and random.random() < 0.5:
                variant += "/menu"
            prefix += variant + ":"
        if (prefix, family) in used or base in bases:
            continue
        used.add((prefix, family))
        bases.add(base)
        tokens.append(prefix + base)
    return " ".join(tokens)


def cls_sites(sites):
    """3 of 4 sites are `cls := ...` (7 of 8 of them one literal, the rest a list of literals,
    conditional pairs and `Tw` values), 1 of 4 a `tw"..."` value."""
    out = ["package bench.cls\n\nimport Styles.*\n\n"]
    shared = [f'  val t{i}: Tw = tw"{cls_literal(set())}"' for i in range(40)]
    out.append("object Shared:\n" + "\n".join(shared) + "\n\n")
    for i in range(sites):
        if i % 500 == 0:
            out.append(f"object Sites{i // 500}:\n")
        used = set()
        if i % 4 == 3:
            out.append(f'  val s{i}: Tw = tw"{cls_literal(used)}"\n')
        elif i % 8 == 7:
            args = [f'"{cls_literal(used)}"']
            for _ in range(random.randint(1, 3)):
                kind = random.random()
                if kind < 0.4:
                    args.append(f'("{cls_literal(used, 2)}", cond)')
                elif kind < 0.7:
                    args.append(f"Shared.t{random.randrange(40)}")
                elif kind < 0.85:
                    args.append(f"(Shared.t{random.randrange(40)}, cond)")
                else:
                    args.append(f'tw"{cls_literal(used, 2)}"')
            out.append(f"  def s{i}(cond: Boolean): Attr = cls := ({', '.join(args)})\n")
        else:
            out.append(f'  def s{i}(cond: Boolean): Attr = cls := "{cls_literal(used)}"\n')
    out.append("\nobject Main:\n  def main(args: Array[String]): Unit =\n    println(Sites0.s0(true).value.length + Sites1.s500(false).value.length)\n")
    return "".join(out)



def main():
    out = sys.argv[1]
    programs = {
        "validate": {"Macros.scala": VALIDATE_MACROS, "Sites.scala": validate(4000), "classes.txt": catalog()},
        "derive": {"Macros.scala": DERIVE_MACROS, "Sites.scala": derive(200, 4000)},
        "quotes": {"Macros.scala": QUOTES_MACROS, "Sites.scala": quotes(5000)},
        "cls": {"Macros.scala": CLS_MACROS, "Sites.scala": cls_sites(4000), "classes.txt": vocabulary()},
    }
    for name, files in programs.items():
        d = os.path.join(out, name)
        os.makedirs(d, exist_ok=True)
        for file, text in files.items():
            with open(os.path.join(d, file), "w") as f:
                f.write(text)
    print(f"{len(programs)} programs in {out}")


main()
