// jars: scala-library cats-kernel-sjs cats-core-sjs
// `cats.syntax.all.*` over the std's Option, Either, List and Validated: the operators, the
// constructors, traverse and its family, mapN and tupled, the Foldable syntax, the Either syntax.
//> using dep org.typelevel::cats-core:2.13.0
import cats.data.{NonEmptyList, Validated, ValidatedNec}
import cats.syntax.all.*

object Main:
  def main(args: Array[String]): Unit =
    println(1 |+| 2)
    println("ab" |+| "cd")
    println(List(1, 2) |+| List(3))
    println(Option(1) |+| Option(2))
    println(Map("a" -> 1) |+| Map("a" -> 2, "b" -> 3))
    println(1 === 1)
    println("a" =!= "b")
    println(List(1, 2) === List(1, 2))
    println(Option("x") === None)
    println(1.show)
    println("s".show)
    println(List(1, 2).show)
    println(Option(3).show)
    println((1, "a").show)
    println(Map(1 -> "a").show)
    println(1.some)
    println(none[Int])
    println(1.asRight[String])
    println("e".asLeft[Int])
    println(List(1, 2, 3).traverse(i => Option(i + 1)))
    println(List(1, 2, 3).traverse(i => if i > 2 then None else Some(i)))
    println(List(Option(1), Option(2)).sequence)
    println(List(Option(1), None).sequence)
    println(List(1, 2, 3).traverse(i => Either.cond(i < 5, i * 2, s"bad $i")))
    println(List(1, 2, 3).traverse(i => Either.cond(i < 2, i * 2, s"bad $i")))
    println(Option(1).traverse(i => List(i, i + 1)))
    println(List(1, 2, 3).foldMap(_ * 2))
    println(List("a", "bb").foldMap(_.length))
    println(Option(2).foldMap(_ + 1))
    println((Option(1), Option("a")).mapN((i, s) => s"$i$s"))
    println((Option(1), Option.empty[String]).mapN((i, s) => s"$i$s"))
    println((Option(1), Option("a"), Option(true)).tupled)
    println((1.asRight[String], 2.asRight[String]).mapN(_ + _))
    println((1.asRight[String], "no".asLeft[Int]).mapN(_ + _))
    println((List(1, 2), List("a", "b")).tupled)
    val v1: ValidatedNec[String, Int] = 1.validNec
    val v2: ValidatedNec[String, Int] = "e2".invalidNec
    val v3: ValidatedNec[String, Int] = "e3".invalidNec
    println((v1, v1).mapN(_ + _))
    println((v1, v2, v3).mapN(_ + _ + _))
    println((v1, v2).tupled)
    println(List(1, 2, 3).parTraverse(i => Either.cond(i < 5, i * 2, s"bad $i")))
    println(List(1, 2, 3).parTraverse(i => Either.cond(i < 2, i * 2, NonEmptyList.one(s"bad $i"))))
    println(List(1, 2).toNel)
    println(List.empty[Int].toNel)
    println(List(1, 2, 3, 4).groupByNel(_ % 2))
    println(List(1, 2, 3).combineAll)
    println(List(Option(1), None, Option(3)).combineAll)
    println(List.empty[String].combineAll)
    println("e".asLeft[Int].leftMap(_.length))
    println(1.asRight[String].leftMap(_.length))
    println(List(1, 2).flatTraverse(i => Option(List(i, i * 10))))
    println(Option(1).void)
    println(List(1, 2).void)
    println(Option(1).whenA(true))
    println(Option(1).whenA(false))
    println(List(1, 2).whenA(false))
    println(Option(1).unlessA(true))
    println(Validated.valid[String, Int](3).map(_ + 1))
    println(Validated.invalid[String, Int]("bad") |+| Validated.invalid("worse"))
    println(v1.toEither)
    println(v2.toEither)
    println(Option(1).toRight("none"))
    println(Option.empty[Int].toValidNec("missing"))
    println(Option(1).orEmpty)
    println(Option.empty[Int].orEmpty)
    println(List(3, 1, 2).sortBy(identity).mkString(","))
    println(List(1, 2, 3).foldLeft(0)(_ + _))
    println(Option(1).as("x"))
    println(List(1, 2).as(0))
    println(List(1, 2, 3).exists(_ > 2))
    println(List(1, 2).traverse_(i => Option(i)))
    println(List(1, 2, 3).find(_ > 1))
    println(List(1, 2, 3).mkString_("[", ",", "]"))
    println(List("a", "b").intercalate("-"))
    println(Option(5).contains_(5))
    println(1.pure[Option])
    println(1.pure[List])
    println(Option(Option(1)).flatten)
    println(List(1, 2).flatMap(i => List(i, i)))
    println(Option(1) <+> Option(2))
    println((None: Option[Int]) <+> Option(2))
    println(List(1) <+> List(2))
    println(1.some.orElse(2.some))
    println(Either.catchNonFatal(throw new RuntimeException("boom")).leftMap(_.getMessage))
    println("x".asLeft[Int].toOption)
    println("x".asLeft[Int].toValidatedNec)
    println(1.asRight[String].toValidated)
    println(NonEmptyList.of(1, 2, 3).reduceLeft(_ + _))
    println(NonEmptyList.of(1, 2, 3).combineAll)
    println(List(1, 2, 3).reduceLeftOption(_ + _))
    println(List(1, 2, 3).minimumOption)
    println(List(1, 2, 3).maximumOption)
    println(List.empty[Int].maximumOption)
    println(List(1, 2, 3).sumAll)
    println(List(1, 2, 3).productAll)
    println(List(1, 2, 3, 4).partitionEither(i => if i % 2 == 0 then Right(i) else Left(i)))
    println(List(1, 2, 3).zipWithIndex)
    println(List("a", "b").zipWithIndex.map(_.swap))
    println(List(1, 2, 3).foldRight(cats.Eval.now(0))((a, b) => b.map(_ + a)).value)
    println(List(1, 2, 3).mapFilter(i => if i > 1 then Some(i * 2) else None))
    println(List(1, 2, 3).filterA(i => Option(i > 1)))
    println(List(1, 2, 3).traverseFilter(x => Option(Option(x).filter(_ % 2 == 1))))
    println(Option(true).ifM(Option("a"), Option("b")))
    println(List(1, 2).flatTap(i => List(i)))
    println((1.asRight[String]: Either[String, Int]).ensure("small")(_ > 5))
    println(1.asRight[String].recover { case _ => 0 })
    println("e".asLeft[Int].recover { case _ => 0 })
    println("e".asLeft[Int].recoverWith { case "e" => 9.asRight[String] })
    println(Either.fromOption(Option(1), "none"))
    println(Either.fromOption(None, "none"))
    println("e".asLeft[Int].valueOr(_.length))
    println(1.asRight[String].getOrElse(0))
    println(1.asRight[String].bimap(_.length, _ + 1))
    println("s".asLeft[Int].bimap(_.length, _ + 1))
    println(1.asRight[String].swap)
    println(Option(1).map2(Option(2))(_ + _))
    println(Option(1).product(Option("a")))
    println(Option(1) *> Option(2))
    println(Option(1) <* Option(2))
    println(Option(1).productR(Option.empty[Int]))
    println(List(1, 2).fproduct(_ * 10))
    println(List(1, 2).tupleLeft("l"))
    println(List(1, 2).tupleRight("r"))
    println(List(List(1), List(2, 3)).flatten)
    println(List(1, 2, 3).size)
    println(List(1, 2, 3).get(1))
    println(List(1, 2, 3).toNel.map(_.head))
    println(Option(1).toList)
    println(List(1, 2, 3).forall(_ > 0))
    println(List(1, 2, 3).count(_ > 1))
    println(List(1, 2, 3).dropWhile_(_ < 2))
    println(List(1, 2, 3).takeWhile_(_ < 3))
    println(List(1, 2, 3).collectFirst { case 2 => "two" })
    println(List(1, 2, 3).collectFirstSome(i => if i > 1 then Some(i) else None))
    println(List(1, 2, 3).foldM(0)((acc, i) => Option(acc + i)))
    println(List(1, 2, 3).unorderedFoldMap(_ * 2))
    println(List(1, 2, 3).sliding2)
    println("a" -> 1)
    println(List(1, 2, 3).zipWithLongIndex)
    println(List("a", "b").mapWithIndex((s, i) => s + i))
    println(List("a", "b").traverseWithIndexM((s, i) => Option(s + i)))
    println(List(1, 2, 3).distinct)
    println(NonEmptyList.of(3, 1, 2).sorted)
    println(NonEmptyList.of(3, 1, 2).distinct)
    println(NonEmptyList.of(1, 2).concatNel(NonEmptyList.of(3)))
    println(NonEmptyList.of(1, 2) ::: NonEmptyList.of(3))
    println(NonEmptyList.of(1, 2).append(3))
    println(NonEmptyList.of(1, 2).prepend(0))
    println(NonEmptyList.of(1, 2).toList)
    println(NonEmptyList.of(1, 2, 3).filter(_ > 1))
    println(NonEmptyList.of(1, 2, 3).map(_ * 2))
    println(NonEmptyList.of(1, 2, 3).groupBy(_ % 2))
    println(NonEmptyList.of(1, 2, 3).groupByNem(_ % 2))
    println(NonEmptyList.of(1, 2, 3).exists(_ > 2))
    println(NonEmptyList.of(1, 2, 3).find(_ > 1))
    println(NonEmptyList.of(1, 2, 3).reverse)
    println(NonEmptyList.of(1, 2, 3).size)
    println(NonEmptyList.of(1, 2, 3).length)
    println(NonEmptyList.of(1, 2, 3).last)
    println(NonEmptyList.of(1, 2, 3).init)
    println(NonEmptyList.of(1, 2, 3).zipWithIndex)
    println(NonEmptyList.of(1, 2).zip(NonEmptyList.of("a", "b")))
    println(NonEmptyList.of(1, 2, 3).mkString_(", "))
    println(NonEmptyList.of(1, 2, 3).show)
    println(NonEmptyList.of(1, 2, 3).traverse(i => Option(i)))
    println(NonEmptyList.of(1, 2).flatMap(i => NonEmptyList.of(i, i)))
    println(NonEmptyList.of(1, 2, 3).toList.toSet)
    println(NonEmptyList.fromList(List(1)))
    println(NonEmptyList.fromListUnsafe(List(1, 2)))
    println(NonEmptyList.fromFoldable(Vector(1, 2)))
    println(NonEmptyList.one(1))
    println(NonEmptyList.of(1, 2, 3).sortBy(-_))
    println(NonEmptyList.of(1, 2, 3).foldLeft(0)(_ + _))
    println(NonEmptyList.of(1, 2, 3).reduce)
    println(NonEmptyList.of("a", "b").reduceLeft(_ + _))
    println(NonEmptyList.of(1, 2, 3) === NonEmptyList.of(1, 2, 3))
    println(NonEmptyList.of(1, 2, 3).collect { case i if i > 1 => i })
    println(NonEmptyList.of(1, 2, 3).toNes)
    println(NonEmptyList.of(1, 2, 3).head)
    println(NonEmptyList.of(1, 2, 3).tail)
    println(NonEmptyList.of((1, "a"), (2, "b")).toNem)
    println(List(1, 2, 3).toNel.get.minimum)
    println(List(1, 2, 3).toNel.get.maximum)
    println(Option(NonEmptyList.of(1)).map(_.head))
