object Main:
  def main(args: Array[String]): Unit =
    println(Integer.bitCount(0xF0F0))
    println(Integer.numberOfLeadingZeros(1))
    println(Integer.numberOfTrailingZeros(8))
    println(Integer.rotateLeft(0x80000001, 3))
    println(Integer.rotateRight(1, 1))
    println(Integer.reverse(1))
    println(Integer.reverseBytes(0x01020304))
    println(Integer.highestOneBit(100))
    println(Integer.toHexString(255) + " " + Integer.toBinaryString(5) + " " + Integer.toOctalString(9))
    println(Integer.parseInt("42") + Integer.parseInt("ff", 16))
    println(Integer.compare(3, 7) + " " + Integer.signum(-9) + " " + Integer.compareUnsigned(-1, 1))
    println(Integer.MAX_VALUE + " " + Integer.MIN_VALUE)
    println(java.lang.Long.bitCount(0xFFL) + " " + java.lang.Long.numberOfTrailingZeros(64L) + " " + java.lang.Long.numberOfLeadingZeros(1L))
    println(java.lang.Long.toHexString(255L) + " " + java.lang.Long.compare(2L, 1L))
    println(java.lang.Math.floorMod(-7, 3) + " " + java.lang.Math.floorDiv(-7, 3) + " " + java.lang.Math.max(2, 9) + " " + java.lang.Math.abs(-4.5))
    println(java.lang.Math.floorMod(-7L, 3L) + " " + Math.sqrt(2.25) + " " + Math.hypot(1.5, 2.0))
    println("" + Character.isDigit('7') + " " + Character.isLetter('x') + " " + Character.toUpperCase('q') + " " + Character.isWhitespace(' ') + " " + Character.digit('f', 16))
    println(java.lang.Double.compare(1.5, 2.5) + " " + java.lang.Double.isNaN(0.0 / 0.0) + " " + java.lang.Double.isInfinite(1.0 / 0.0))
    println(java.lang.Boolean.compare(true, false) + " " + java.lang.Boolean.parseBoolean("TRUE"))
    val a = Array(5, 3, 9, 1)
    java.util.Arrays.sort(a)
    println(java.util.Arrays.toString(a))
    val b = java.util.Arrays.copyOf(a, 6)
    println(java.util.Arrays.toString(b))
    val c = java.util.Arrays.copyOfRange(a, 1, 3)
    println(java.util.Arrays.toString(c))
    java.util.Arrays.fill(c, 7)
    println(java.util.Arrays.toString(c) + " " + java.util.Arrays.equals(a, a.clone()))
    val d = new Array[Int](4)
    System.arraycopy(a, 0, d, 1, 3)
    println(java.util.Arrays.toString(d))
    println("" + java.util.Objects.equals("a", "a") + " " + java.util.Objects.equals(null, "a") + " " + java.util.Objects.isNull(null))
    println(java.util.Objects.hashCode(null) + " " + java.util.Objects.toString(null))
    val sb = new java.lang.StringBuilder()
    sb.append("ab").append(1).append('c')
    println(sb.length + " " + sb.charAt(2) + " " + sb.toString)
    sb.insert(0, "x")
    sb.reverse()
    println(sb.toString)
    sb.setLength(2)
    println(sb.toString)
    println(Integer.toString(255, 2) + " " + java.lang.Long.toString(255L, 16))
    println(java.lang.Integer.toUnsignedString(-1))
    println(Integer.divideUnsigned(-1, 2) + " " + Integer.remainderUnsigned(-1, 2))
