package p
import scala.util.Try
@main def main(): Unit =
  println("main start")
  println(fileA2)
  println(fileALazy)
  println("enum companion")
  println(Color.Red.next)
  println(Color.default)
  println(Shape.Sq(2))
  println(Shape.unit)
  println(P(3))
  println(P.origin)
  println("object cycle")
  println(Cyc1.v)
  println("lazy failure")
  println(Try(LazyFail.flaky).isFailure)
  println(LazyFail.flaky)
  println(LazyFail.attempts)
  println(LazyFail.reentrant)
  println(Planet.Venus.mass)
  println(Planet.heaviest)
  println(Q.make(2))
  println(Color.valueOf("Blue"))
  println("main end")
