// The images of browserdemo's page, a generator of sources that the build's own binary runs:
//   teq interp scripts/images.scala -- <application directory> <output directory>
// For each image folder under the application's assets/images/, a Scala object with a val per
// `.svg` file under it, written into the output directory (the one the build appends), and the
// module assets/images.js naming the files, which the page's bundler serves; each file written only
// when its text changes, so that a build that runs it again finds its sources as they were.
import java.nio.file.{Files, Path, Paths}
import scala.jdk.CollectionConverters.*

object Images:
  private val folders = List("shapes" -> "ShapeImages", "marks" -> "MarkImages")
  private val generated = "Generated by scripts/images.scala. Do not edit."

  def main(args: Array[String]): Unit =
    if args.length != 2 then
      System.err.println("usage: teq interp scripts/images.scala -- <application directory> <output directory>")
      sys.exit(2)
    val app = Paths.get(args(0))
    val out = Paths.get(args(1))
    val found = folders.map((folder, name) => (folder, name, svgs(app.resolve("assets/images").resolve(folder))))
    val written = (writeIfChanged(app.resolve("assets/images.js"), module(found)) :: found.map { (folder, name, files) =>
      writeIfChanged(out.resolve("demo/images").resolve(name + ".scala"), scalaObject(folder, name, files))
    }).count(identity)
    println(s"images: ${found.map(_._3.size).sum} images, $written files written")

  // The `.svg` files under the folder, as paths relative to it with `/` between their names.
  private def svgs(dir: Path): List[String] =
    if !Files.isDirectory(dir) then Nil
    else
      val walk = Files.walk(dir)
      try
        walk.iterator.asScala.toList
          .filter(p => Files.isRegularFile(p) && p.getFileName.toString.endsWith(".svg"))
          .map(p => dir.relativize(p).toString.replace('\\', '/').stripSuffix(".svg"))
          .sorted
      finally walk.close()

  private def identifier(file: String): String =
    val parts = file.split('/')
    val name = parts.head + parts.tail.map(_.capitalize).mkString
    require(name.matches("[a-z][a-zA-Z0-9]*"), s"an image's name is a Scala identifier: $file.svg")
    name

  private def module(found: List[(String, String, List[String])]): String =
    val sections = for (folder, _, files) <- found yield
      val entries = files.map(f => s"""  ${identifier(f)}: "/assets/images/$folder/$f.svg",""").mkString("\n")
      s"export const $folder = {\n$entries\n};\n"
    s"// $generated\n\n" + sections.mkString("\n")

  private def scalaObject(folder: String, name: String, files: List[String]): String =
    val vals = files.map(f => s"""  val ${identifier(f)}: String = "/assets/images/$folder/$f.svg"""").mkString("\n")
    s"""package demo.images
       |
       |// $generated
       |object $name:
       |$vals
       |  val all: Seq[String] = Seq(${files.map(identifier).mkString(", ")})
       |""".stripMargin

  // Whether the file was written: only when its text changes.
  private def writeIfChanged(file: Path, content: String): Boolean =
    val changed = !Files.exists(file) || Files.readString(file) != content
    if changed then
      Files.createDirectories(file.getParent)
      Files.writeString(file, content)
    changed
