package meridian.web.vdom

object Tags:
  private def tag(name: String): VdomTag = new VdomTag(name, Nil)
  val div: VdomTag = tag("div")
  val span: VdomTag = tag("span")
  val button: VdomTag = tag("button")
  val label: VdomTag = tag("label")
  val p: VdomTag = tag("p")
  val h1: VdomTag = tag("h1")
  val h2: VdomTag = tag("h2")
  val h3: VdomTag = tag("h3")
  val td: VdomTag = tag("td")
  val th: VdomTag = tag("th")
  val tr: VdomTag = tag("tr")
  val a: VdomTag = tag("a")
  val li: VdomTag = tag("li")
  val ul: VdomTag = tag("ul")
  val ol: VdomTag = tag("ol")
  val img: VdomTag = tag("img")
  val table: VdomTag = tag("table")
  val thead: VdomTag = tag("thead")
  val tbody: VdomTag = tag("tbody")
  val section: VdomTag = tag("section")
  val form: VdomTag = tag("form")
  val textarea: VdomTag = tag("textarea")
  val footer: VdomTag = tag("footer")
  val headerTag: VdomTag = tag("header")
  val select: VdomTag = tag("select")
  val option: VdomTag = tag("option")
  val code: VdomTag = tag("code")
  val pre: VdomTag = tag("pre")
  val nav: VdomTag = tag("nav")
  val mainTag: VdomTag = tag("main")
  val hr: VdomTag = tag("hr")
  val br: VdomTag = tag("br")
  val small: VdomTag = tag("small")
  val strong: VdomTag = tag("strong")
  val em: VdomTag = tag("em")
  val dialog: VdomTag = tag("dialog")
  val aside: VdomTag = tag("aside")
  val article: VdomTag = tag("article")
  val fieldset: VdomTag = tag("fieldset")
  val legend: VdomTag = tag("legend")
  val progress: VdomTag = tag("progress")

  object input:
    val text: VdomTag = new VdomTag("input", List(new AttrMod("type", "text")))
    val number: VdomTag = new VdomTag("input", List(new AttrMod("type", "number")))
    val checkbox: VdomTag = new VdomTag("input", List(new AttrMod("type", "checkbox")))
    val radio: VdomTag = new VdomTag("input", List(new AttrMod("type", "radio")))
    val file: VdomTag = new VdomTag("input", List(new AttrMod("type", "file")))
    val date: VdomTag = new VdomTag("input", List(new AttrMod("type", "date")))
    val time: VdomTag = new VdomTag("input", List(new AttrMod("type", "time")))
    def apply(mods: Mod*): VdomTag = new VdomTag("input", mods.toList)

  object svg:
    val svg: VdomTag = tag("svg")
    val g: VdomTag = tag("g")
    val rect: VdomTag = tag("rect")
    val text: VdomTag = tag("text")
    val circle: VdomTag = tag("circle")
    val pathTag: VdomTag = tag("path")

  def custom(name: String): VdomTag = tag(name)
