@main def run(): Unit =
  println(Kinds.kind(Some(1)))
  println(Kinds.kind(Some("s")))
  println(Kinds.kind(Some(List(1))))
  println(Kinds.kind((1: Any, "x")))
  println(Kinds.lower(Some(1)))
  println(Kinds.lower(Some("s")))
  println(Kinds.dependent((Array("s"), Array(1))))
  println(Kinds.dependent((Array("s"), Array("t"))))
  println(Kinds.dependent((Array("s"), Array[CharSequence]("t"))))
  println(Kinds.reversed((Array(1), Array("s"))))
  println(Kinds.reversed((Array[CharSequence]("t"), Array("s"))))
  println(Kinds.values(List(1, 2)))
  println(Kinds.values(List("s")))
  println(Kinds.param((i: Int) => i + 1))
  println(Kinds.param((b: Boolean) => 1))
