// jars: scala-library javafix
// Checks with no error: Java classes read from the JDK's ct.sym and from a jar of javac's
// class files (tests/classfile/fixtures), against scala-library.
package fix
import java.util.{ArrayList, HashMap, Optional, Arrays, Comparator}
object Main:
  def main(args: Array[String]): Unit =
    val xs = new ArrayList[String]()
    xs.add("b")
    xs.add("a")
    println(xs.size())
    println(xs.get(0))
    println(xs.isEmpty)
    val m = new HashMap[String, Int]()
    m.put("k", 1)
    println(m.get("k"))
    println(m.containsKey("k"))
    val boxed = new HashMap[String, Integer]()
    boxed.put("k", Integer.valueOf(1))
    println(boxed.get("k").intValue)
    val opt = Optional.of(1).map(x => x + 1)
    println(opt.get())
    println(Optional.empty[String]().isPresent)
    val date = java.time.LocalDate.of(2024, 1, 2).plusDays(3)
    println(date.getDayOfMonth)
    println(Integer.parseInt("42") + 1)
    val d: Double = Math.max(1, 2.5)
    println(d)
    println(System.currentTimeMillis() > 0L)
    val sb = new java.lang.StringBuilder()
    println(sb.append("a").append(1).toString)
    println(Arrays.asList("a", "b").size())
    println("abc".repeat(2))
    println("a,b".split(",").length)
    val s: String = String.valueOf(1)
    println(s)
    println("abc".toUpperCase.length)
    val byLength: Comparator[String] = Comparator.comparingInt(str => str.length)
    println(byLength.reversed().compare("a", "bb") > 0)
    println(Color.values().length)
    println(Color.RED.label())
    println(Color.valueOf("GREEN").rgb)
    val p = Pair.twin("x")
    println(p.first())
    val g = new Generics[Integer](Integer.valueOf(5))
    println(g.value)
    println(Generics.LIMIT + Generics.NAME)
    println(Generics.listOf("a", "b").size())
    println(Named.join("-", "a", "b"))
    println(Shapes.unit().describe())
    val shape: Shapes = new Square(2.0)
    println(shape.area())
    println(Outer.nested().isInstanceOf[Runnable])
    val any = new ArrayList[Any]()
    any.add(1)
    any.add("s")
    println(any.size())
    println(java.util.Objects.equals(1, 1))
    println(java.util.Objects.hash(1, "a") != 0)
