// The js package on its own: no imports, so this stays a plain script.

case class Point(x: Int, y: Int)

class Bag(items: List[String]):
  def foreach[U](f: String => U): Unit = items.foreach(f)

def show(x: Any): String = js.cast[String](js.call(js.global("JSON"), "stringify", x))

def objects(): Unit =
  val o = js.obj("name" -> "teq", "answer" -> 42, "nested" -> js.obj("ok" -> true))
  println(show(o))
  println(js.get(o, "name"))
  println(js.get(js.get(o, "nested"), "ok"))
  js.set(o, "answer", 43)
  js.set(o, "extra", List(1, 2).length)
  println(show(o))
  println(show(js.obj()))
  val pairs = List("a" -> 1, "b" -> 2)
  println(show(js.obj(pairs*)))
  println(show(js.obj(Map("k" -> "v", "n" -> 1.5).toList*)))
  println(show(js.obj(Vector("x" -> 1).map(p => (p._1 + "!", p._2 + 1))*)))
  val answer: Int = js.cast[Int](js.get(o, "answer"))
  println(answer + 1)
  println(js.isUndefined(js.get(o, "missing")))
  println(js.call(o, "hasOwnProperty", "name"))
  println(js.get(Point(3, 4), "y"))

def arrays(): Unit =
  val arr = js.array(1, "two", 3.5, true)
  println(show(arr))
  println(js.get(arr, "length"))
  println(show(js.array()))
  println(show(js.array(List(1, 2, 3)*)))
  println(show(js.array(Vector("a", "b")*)))
  js.call(arr, "push", 5, 6)
  println(show(arr))
  val back = js.toList[Int](js.array(1, 2, 3))
  println(back)
  println(back.map(_ + 1).sum)
  println(js.toList[String](js.call("a-b-c", "split", "-")))
  val typed: Array[Int] = js.arrayFrom[Int](List(7, 8))
  println(typed.length + typed(1))

def iterables(): Unit =
  println(show(js.arrayFrom[Any](List(1, 2, 3))))
  println(show(js.arrayFrom[Any](Vector("v"))))
  println(show(js.arrayFrom[Any](Set("x", "y"))))
  println(show(js.arrayFrom[Any](1 to 4)))
  println(show(js.arrayFrom[Any](Bag(List("p", "q")))))
  println(show(js.arrayFrom[Any](Some(5))))
  println(show(js.arrayFrom[Any](Map(1 -> "one"))))
  println(js.toList[Int](Vector(1, 2)))
  val forOf = js.construct(js.global("Function"), "xs", "let s = 0; for (const x of xs) s += x; return s;")
  println(js.apply(forOf, List(1, 2, 3)))
  println(js.apply(forOf, 1 until 5))
  val spread = js.construct(js.global("Function"), "xs", "return Math.max(...xs);")
  println(js.apply(spread, Vector(4, 9, 2)))

def values(): Unit =
  println(js.typeOf("s"))
  println(js.typeOf(1))
  println(js.typeOf(1.5))
  println(js.typeOf(true))
  println(js.typeOf(1L))
  println(js.typeOf('c'))
  println(js.typeOf(()))
  println(js.typeOf((x: Int) => x))
  println(js.typeOf(Point(1, 2)))
  println(js.typeOf(js.nullValue))
  println(js.typeOf(js.undefined))
  println(js.isUndefined(js.undefined))
  println(js.isUndefined(()))
  println(js.isNull(js.nullValue))
  println(js.isNull(js.undefined))
  println(js.isNull(0))

def globals(): Unit =
  val math = js.global("Math")
  println(js.call(math, "max", 3, 9, 4))
  println(js.call(math, "max", List(3, 19, 4)*))
  println(js.apply(js.get(math, "min"), 4, 2, 8))
  println(js.apply((a: Int, b: Int) => a + b, 1, 2))
  println(js.isUndefined(js.global("noSuchGlobal")))
  println(js.get(js.globalThis, "Math") == math)
  val date = js.construct(js.global("Date"), 0)
  println(js.call(date, "toISOString"))
  val map = js.construct(js.global("Map"))
  js.call(map, "set", "k", 1)
  js.call(map, "set", "l", 2)
  println(js.get(map, "size"))
  println(js.toList[Any](js.call(map, "keys")))
  val n: Double = js.cast[Double](js.call(js.global("Number"), "parseFloat", "2.5"))
  println(n * 2)

@main def main(): Unit =
  objects()
  arrays()
  iterables()
  values()
  globals()
